library(arrow)
library(dplyr)
library(ggplot2)
library(patchwork)
library(sf)
library(tidyr)
library(readxl)

theme_set(theme_bw() + theme(axis.line = element_line(linewidth = 0.3),
                             legend.background = element_rect(fill = alpha("white", 0.5)),
                             legend.key.height = unit(0.85, "line"),
                             legend.margin = margin(),
                             legend.title = element_text(size = 10),
                             panel.border = element_blank(),
                             plot.title = element_text(size = 10)))

# read .feather files generated by Elliott iLand runs, ~
trajectoryLength = 78 # years
stands2022 = as_tibble(st_drop_geometry(st_read("GIS/Planning/Elliott State Forest + Hakki stands 2016.gpkg", layer = "unified stands 2022 property boundary split", quiet = TRUE))) %>%
  group_by(standID2016) %>%
  summarize(standAge2016 = standAge2016[1], isPlantation = any(isPlantation), standArea = sum(standArea))

featherReadStart = Sys.time() # ~14 s, 9900X
resourceUnitTrajectories = read_feather(paste0("iLand/output/Elliott ", trajectoryLength, " year resource unit trajectories.feather"), mmap = FALSE) %>%
  mutate(qmd = sqrt(treeBasalArea / (0.01^2 * pi/4 * treesPerHectare)),
         species = factor(species, labels = c("all", "psme"), levels = c(0, 202)))
standTrajectories = left_join(read_feather(paste0("iLand/output/Elliott ", trajectoryLength, " year stand trajectories.feather"), mmap = FALSE) %>%
                                mutate(qmd = sqrt(treeBasalArea / (0.01^2 * pi/4 * treesPerHectare))),
                              stands2022,
                              by = join_by(stand == standID2016))
threePG = read_feather(paste0("iLand/output/Elliott ", trajectoryLength, " year 3-PG.feather"), mmap = FALSE) %>%
  mutate(decimalYear = year + 1/12 * (month - 0.5),
         species = factor(species, labels = c("all", "psme"), levels = c(0, 202)),
         uniqueID = paste(resourceUnit, species))
Sys.time() - featherReadStart


## basic plots
# Reineke stand density diagrams by resource unit and stand (with workaround for https://github.com/tidyverse/ggplot2/issues/4935)
logBreaks = c(1, 2, 3, 5, 10, 20, 30, 50, 100, 200, 500, 1000, 4000)
logMinorBreaks = c(4, 6, 7, 8, 9, 40, 60, 70, 80, 90, 300, 400, 600, 700, 800, 900, 2000, 3000)
sdi = crossing(tph = c(1, 1000, 4000), sdi = c(10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1500, 2000)) %>% mutate(qmd = 25 * (sdi / tph)^(1/1.605))

ggplot() +
  geom_path(aes(x = tph, y = qmd, group = sdi), sdi, color = "grey90", linetype = if_else(sdi$sdi == 1500, "longdash", "solid"), linewidth = if_else(sdi$sdi %in% c(10, 100, 1000), 0.5, 0.25)) +
  geom_path(aes(x = treesPerHectare, y = qmd, color = liveStemVolume, group = stand, linewidth = standArea), standTrajectories, arrow = arrow(length = unit(0.25, "line"), type = "closed")) +
  #geom_path(aes(x = treesPerHectare, y = qmd, color = liveStemVolume, group = stand, linewidth = standArea), standTrajectories) + # stand 0 has NA area
  #geom_label(aes(x = 1300, y = 15, label = "missing\ntrees"), color = "red", fill = alpha("white", 0.7), label.padding = unit(0.15, "line"), label.size = NA, hjust = 0.5, size = 3.0, vjust = 0.4) +
  geom_label(aes(x = tph, y = qmd, label = if_else(sdi == 2000, paste("SDI =\n", sdi), as.character(sdi))), sdi %>% filter(tph == 4000, sdi %in% c(1000, 2000)), color = "grey70", fill = alpha("white", 0.7), label.padding = unit(0.1, "line"), label.size = NA, size = 3.0, vjust = c(0.5, 0.25)) +
  labs(x = "stand density, mean trees per hectare", y = "stand QMD, cm", color = "live stem\nvolume,\nm³ ha ¹", linewidth = "stand\narea, ha", title = NULL) +
  coord_cartesian(xlim = c(12, 4000), ylim = c(11, 200)) +
  guides(color = guide_colorbar(order = 1), linewidth = guide_legend(order = 2)) +
  #scale_color_viridis_c(breaks = seq(0, 2000, by = 500), limits = c(0, 2000)) +
  scale_color_viridis_c(breaks = seq(0, 5000, length.out = 5), limits = c(0, 5000)) +
  scale_linewidth_continuous(limits = c(0, 150), range = c(0.1, 3.0)) +
  scale_x_log10(breaks = logBreaks, minor_breaks = logMinorBreaks) +
  scale_y_log10(breaks = logBreaks, minor_breaks = logMinorBreaks) +
  theme(legend.spacing.y = unit(0.4, "line"))
#ggsave("iLand/output/stand trajectories 2025-05-06 iLand.png", units = "cm", width = 22, height = 10.9, dpi = 200)


## 3-PG 
# modifiers: histograms (first block of plots) take a few seconds, line plot take a few minutes at forest scale even if
# only one decade of projection
ggplot(threePG %>% filter(year > 2021)) + # 3-PG outputs are all zero in initialization year
  geom_histogram(aes(x = co2Modifier, y = after_stat(density), fill = "CO2"), binwidth = 0.002) +
  guides(color = guide_legend(ncol = 4)) +
  labs(x = bquote("3-PG CO"[2]*" modifier"), y = "probability density", color = NULL) +
  scale_fill_manual(values = c("grey35")) +
  theme(legend.position = "null") +
ggplot(threePG %>% filter(year > 2021)) + # 3-PG outputs are all zero in initialization year
  geom_histogram(aes(x = soilWaterModifier, y = after_stat(density), fill = "soil water"), binwidth = 0.01) +
  guides(color = guide_legend(ncol = 4)) +
  labs(x = "3-PG soil water modifier", y = NULL, color = NULL) +
  scale_fill_manual(values = "blue2") +
  theme(legend.position = "null") +
ggplot(threePG %>% filter(year > 2021)) + # 3-PG outputs are all zero in initialization year
  geom_histogram(aes(x = temperatureModifier, y = after_stat(density), fill = "temperature"), binwidth = 0.01) +
  guides(color = guide_legend(ncol = 4)) +
  labs(x = "3-PG temperature modifier", y = "probability density", color = NULL) +
  scale_fill_manual(values = "darkorange2") +
  theme(legend.position = "null") +
ggplot(threePG %>% filter(year > 2021)) + # 3-PG outputs are all zero in initialization year
  geom_histogram(aes(x = vpdModifier, y = after_stat(density), fill = "VPD"), binwidth = 0.01) +
  guides(color = guide_legend(ncol = 4)) +
  labs(x = "3-PG VPD modifier", y = NULL, color = NULL) +
  scale_fill_manual(values = c("darkviolet")) +
  theme(legend.position = "null") +
plot_layout(nrow = 2, ncol = 2)

ggplot(threePG %>% filter(year > 2021, resourceUnit == resourceUnit[1])) + # 3-PG outputs are all zero in initialization year, CO₂ is the same for all resource units
  geom_path(aes(x = decimalYear, y = co2Modifier, color = "CO2", group = uniqueID)) +
  guides(color = guide_legend(ncol = 4)) +
  labs(x = NULL, y = bquote("CO"[2]*" modifier"), color = NULL) +
  scale_color_manual(values = c("grey35")) +
  scale_x_continuous(breaks = seq(2022, 2040, by = 4)) +
  theme(legend.position = "null") +
ggplot(threePG %>% filter(year > 2021)) + # 3-PG outputs are all zero in initialization year
  geom_path(aes(x = decimalYear, y = soilWaterModifier, color = "soil water", group = uniqueID), alpha = 0.05) +
  coord_cartesian(ylim = c(0.2, 1)) + 
  guides(color = guide_legend(ncol = 4)) +
  labs(x = NULL, y = "soil water modifier", color = NULL) +
  scale_color_manual(values = "blue2") +
  scale_x_continuous(breaks = seq(2022, 2040, by = 4)) +
  theme(legend.position = "null") +
ggplot(threePG %>% filter(year > 2021)) + # 3-PG outputs are all zero in initialization year
  geom_path(aes(x = decimalYear, y = temperatureModifier, color = "temperature", group = uniqueID), alpha = 0.05) +
  coord_cartesian(ylim = c(0.2, 1)) + 
  guides(color = guide_legend(ncol = 4)) +
  labs(x = "calendar year", y = "temperature modifier", color = NULL) +
  scale_color_manual(values = "darkorange2") +
  scale_x_continuous(breaks = seq(2022, 2040, by = 4)) +
  theme(legend.position = "null") +
ggplot(threePG %>% filter(year > 2021)) + # 3-PG outputs are all zero in initialization year
  geom_path(aes(x = decimalYear, y = vpdModifier, color = "VPD", group = uniqueID), alpha = 0.05) +
  coord_cartesian(ylim = c(0.2, 1)) + 
  guides(color = guide_legend(ncol = 4)) +
  labs(x = "calendar year", y = "VPD modifier", color = NULL) +
  scale_color_manual(values = c("darkviolet")) +
  scale_x_continuous(breaks = seq(2022, 2040, by = 4)) +
  theme(legend.position = "null") +
  plot_layout(nrow = 2, ncol = 2)
ggsave("Presentation/3-PG modifiers 2022-2032 2022-09-09.png", units = "cm", width = 10, height = 9, dpi = 300)

# water cycle
ggplot(threePG %>% filter(year > 2021)) + # 3-PG outputs are all zero in initialization year
  geom_path(aes(x = decimalYear, y = infiltration, color = "infiltration, mm", group = uniqueID), alpha = 0.15) +
  geom_path(aes(x = decimalYear, y = evapotranspiration, color = "evapotranspiration, mm", group = uniqueID), alpha = 0.15) +
  geom_path(aes(x = decimalYear, y = soilWaterPotential, color = "matric potential, kPa", group = uniqueID), alpha = 0.15) +
  labs(x = "calendar year", y = "water flow, mm, or matric potential, kPa", color = NULL) +
  scale_color_manual(breaks = c("infiltration, mm", "evapotranspiration, mm", "matric potential, kPa"), values = c("blue2", "green3", "grey25")) +
  scale_x_continuous(breaks = seq(2022, 2032, by = 2)) +
  theme(legend.justification = c(0, 1), legend.position = c(0.02, 0.99))
ggsave("Presentation/3-PG water cycle 2022-2032 2022-09-09.png")