library(quantreg)

## height interquartile ranges
psmeHeightFromDiameterMichaelisMentenQ25 = nlrq(TotalHt ~ 1.37 + (a1 + a1p*isPlantation)*DBH^b1 / (a2 + a2p * isPlantation + DBH^b1), psme2016, start = list(a1 = 70.4, a1p = -25.3, a2 = 660, a2p = -348, b1 = 1.61), tau = 0.25)
psmeHeightFromDiameterMichaelisMentenQ75 = nlrq(TotalHt ~ 1.37 + (a1 + a1p*isPlantation)*DBH^b1 / (a2 + a2p * isPlantation + DBH^b1), psme2016, start = list(a1 = 93.9, a1p = -10.3, a2 = 108, a2p = 4.8, b1 = 1.13), tau = 0.75)
#psmeHeightFromDiameterSharmaPartonQ75 = nlrq(TotalHt ~ 1.37 + a1*topHeight^a2*(1 - exp(b1*(tph/standBasalAreaPerHectare)^b2*DBH))^b3, psme2016, start = list(a1 = 52.41, a2 = 0.135, b1 = -0.017, b2 = -0.071, b3 = 1.02), tau = 0.75)
#psmeHeightFromDiameterSharmaPartonQ75 = nlrq(TotalHt ~ 1.37 + a1*topHeight^(a2 + a2p * isPlantation)*(1 - exp((b1 + b1p * isPlantation)*(tph/standBasalAreaPerHectare)^(b2 + b2p * isPlantation)*DBH))^(b3 + b3p * isPlantation), psme2016, start = list(a1 = 52.41, a2 = 0.135, a2p = -0, b1 = -0.017, b1p = -0, b2 = -0.071, b2p = -0, b3 = 1.02, b3p = -0), tau = 0.75)
psmeHeightFromDiameterSharmaPartonQ25 = nlrq(TotalHt ~ 1.37 + a1*topHeight^(a2 + a2p * isPlantation)*(1 - exp((b1 + b1p * isPlantation)*(tph/standBasalAreaPerHectare)^(b2 + b2p * isPlantation)*DBH))^(b3 + b3p * isPlantation), psme2016, start = list(a1 = 42.8, a2 = 0.114, a2p = -0.045, b1 = -0.023, b1p = -0.026, b2 = 0.039, b2p = -0.258, b3 = 1.94, b3p = -0.94), tau = 0.25)
psmeHeightFromDiameterSharmaPartonQ75 = nlrq(TotalHt ~ 1.37 + a1*topHeight^(a2 + a2p * isPlantation)*(1 - exp((b1 + b1p * isPlantation)*(tph/standBasalAreaPerHectare)^(b2 + b2p * isPlantation)*DBH))^(b3 + b3p * isPlantation), psme2016, start = list(a1 = 57.5, a2 = 0.065, a2p = 0.071, b1 = -0.021, b1p = 0.010, b2 = 0.028, b2p = -0.115, b3 = 1.39, b3p = -0.573), tau = 0.75)

alruHeightFromDiameterMichaelisMentenQ25 = nlrq(TotalHt ~ 1.37 + (a1 + a1p * isPlantation)*DBH^(b1 + b1p * isPlantation) / (a2 + + DBH^(b1 + b1p * isPlantation)), alru2016, start = list(a1 = 22.7, a1p = 5.55, a2 = 101, b1 = 1.54, b1p = -0.067), tau = 0.25)
alruHeightFromDiameterMichaelisMentenQ75 = nlrq(TotalHt ~ 1.37 + (a1 + a1p * isPlantation)*DBH^(b1 + b1p * isPlantation) / (a2 + + DBH^(b1 + b1p * isPlantation)), alru2016, start = list(a1 = 31.6, a1p = 5.53, a2 = 49.6, b1 = 1.37, b1p = -0.099), tau = 0.75)
alruHeightFromDiameterSharmaPartonQ25 = nlrq(TotalHt ~ 1.37 + a1*topHeight^(a2 + a2p * isPlantation)*(1 - exp(b1*(tph/standBasalAreaPerHectare)^(b2 + b2p * isPlantation)*DBH))^(b3 + b3p * isPlantation), alru2016, start = list(a1 = 21.3, a2 = 0.038, a2p = 0.068, b1 = -0.039, b2 = 0.084, b2p = -0.127, b3 = 1.19, b3p = -0.14), tau = 0.25)
alruHeightFromDiameterSharmaPartonQ75 = nlrq(TotalHt ~ 1.37 + a1*topHeight^(a2 + a2p * isPlantation)*(1 - exp(b1*(tph/standBasalAreaPerHectare)^(b2 + b2p * isPlantation)*DBH))^(b3 + b3p * isPlantation), alru2016, start = list(a1 = 21.3, a2 = 0.038, a2p = 0.068, b1 = -0.039, b2 = 0.084, b2p = -0.127, b3 = 1.19, b3p = -0.14), tau = 0.75)

tsheHeightFromDiameterMichaelisMentenQ25 = nlrq(TotalHt ~ 1.37 + (a1 + a1p * isPlantation)*DBH^b1 / (a2 + a2p * isPlantation + DBH^b1), tshe2016, start = list(a1 = 74.8, a1p = -19.0, a2 = 200, a2p = -77.4, b1 = 1.264), tau = 0.25)
tsheHeightFromDiameterMichaelisMentenQ75 = nlrq(TotalHt ~ 1.37 + (a1 + a1p * isPlantation)*DBH^b1 / (a2 + a2p * isPlantation + DBH^b1), tshe2016, start = list(a1 = 74.8, a1p = -19.0, a2 = 200, a2p = -77.4, b1 = 1.264), tau = 0.75)

acmaHeightFromDiameterMichaelisMentenQ25 = nlrq(TotalHt ~ 1.37 + a1*DBH^b1 / (a2 + a2p * isPlantation + DBH^b1), acma2016, start = list(a1 = 41.2, a2 = 49.0, a2p = -9.29, b1 = 0.986), tau = 0.25)
acmaHeightFromDiameterMichaelisMentenQ75 = nlrq(TotalHt ~ 1.37 + a1*DBH^b1 / (a2 + a2p * isPlantation + DBH^b1), acma2016, start = list(a1 = 41.2, a2 = 49.0, a2p = -9.29, b1 = 0.986), tau = 0.75)

umcaHeightFromDiameterMichaelisMentenQ25 = nlrq(TotalHt ~ 1.37 + (a1 + a1p*isPlantation)*DBH^b1 / (a2 + a2p * isPlantation + DBH^b1), umca2016, start = list(a1 = 21.4, a1p = -4.37, a2 = 43.8, a2p = -20.0, b1 = 1.27), tau = 0.25)
umcaHeightFromDiameterMichaelisMentenQ75 = nlrq(TotalHt ~ 1.37 + (a1 + a1p*isPlantation)*DBH^b1 / (a2 + a2p * isPlantation + DBH^b1), umca2016, start = list(a1 = 21.4, a1p = -4.37, a2 = 43.8, a2p = -20.0, b1 = 1.27), tau = 0.75)

thplHeightFromDiameterMichaelisMentenQ25 = nlrq(TotalHt ~ 1.37 + (a1 + a1p * isPlantation) * DBH^b1 / (a2 + a2p * isPlantation + DBH^b1), thpl2016, start = list(a1 = 70.3, a1p = -18.7, a2 = 200, a2p = -68.2, b1 = 1.176), tau = 0.25)
thplHeightFromDiameterMichaelisMentenQ75 = nlrq(TotalHt ~ 1.37 + (a1 + a1p * isPlantation) * DBH^b1 / (a2 + a2p * isPlantation + DBH^b1), thpl2016, start = list(a1 = 70.3, a1p = -18.7, a2 = 200, a2p = -68.2, b1 = 1.176), tau = 0.75)

otherHeightFromDiameterMichaelisMentenQ25 = nlrq(TotalHt ~ 1.37 + a1*DBH^b1 / (a2 + DBH^b1), other2016, start = list(a1 = 34.6, a2 = 40.2, b1 = 1.03), tau = 0.25)
otherHeightFromDiameterMichaelisMentenQ75 = nlrq(TotalHt ~ 1.37 + a1*DBH^b1 / (a2 + DBH^b1), other2016, start = list(a1 = 34.6, a2 = 40.2, b1 = 1.03), tau = 0.75)

heightIqr = bind_rows(tibble(species = "PSME", name = "Michaelis-Menten", fitting = "nlrq", DBH = psme2016$DBH, isPlantation = psme2016$isPlantation, q25 = predict(psmeHeightFromDiameterMichaelisMentenQ25), q75 = predict(psmeHeightFromDiameterMichaelisMentenQ75)),
                      tibble(species = "PSME", name = "Sharma-Parton", fitting = "nlrq", DBH = psme2016$DBH, isPlantation = psme2016$isPlantation, q25 = predict(psmeHeightFromDiameterSharmaPartonQ25), q75 = predict(psmeHeightFromDiameterSharmaPartonQ75)),
                      tibble(species = "ALRU2", name = "Michaelis-Menten", fitting = "nlrq", DBH = alru2016$DBH, isPlantation = alru2016$isPlantation, q25 = predict(alruHeightFromDiameterMichaelisMentenQ25), q75 = predict(alruHeightFromDiameterMichaelisMentenQ75)),
                      tibble(species = "ALRU2", name = "Sharma-Parton", fitting = "nlrq", DBH = alru2016$DBH, isPlantation = alru2016$isPlantation, q25 = predict(alruHeightFromDiameterSharmaPartonQ25), q75 = predict(alruHeightFromDiameterSharmaPartonQ75)),
                      tibble(species = "TSHE", name = "Michaelis-Menten", fitting = "nlrq", DBH = tshe2016$DBH, isPlantation = tshe2016$isPlantation, q25 = predict(tsheHeightFromDiameterMichaelisMentenQ25), q75 = predict(tsheHeightFromDiameterMichaelisMentenQ75)),
                      tibble(species = "ACMA3", name = "Michaelis-Menten", fitting = "nlrq", DBH = acma2016$DBH, isPlantation = acma2016$isPlantation, q25 = predict(acmaHeightFromDiameterMichaelisMentenQ25), q75 = predict(acmaHeightFromDiameterMichaelisMentenQ75)),
                      tibble(species = "UMCA", name = "Michaelis-Menten", fitting = "nlrq", DBH = umca2016$DBH, isPlantation = umca2016$isPlantation, q25 = predict(umcaHeightFromDiameterMichaelisMentenQ25), q75 = predict(umcaHeightFromDiameterMichaelisMentenQ75)),
                      tibble(species = "THPL", name = "Michaelis-Menten", fitting = "nlrq", DBH = thpl2016$DBH, isPlantation = thpl2016$isPlantation, q25 = predict(thplHeightFromDiameterMichaelisMentenQ25), q75 = predict(thplHeightFromDiameterMichaelisMentenQ75)),
                      tibble(species = "other", name = "Michaelis-Menten", fitting = "nlrq", DBH = other2016$DBH, isPlantation = other2016$isPlantation, q25 = predict(otherHeightFromDiameterMichaelisMentenQ25), q75 = predict(otherHeightFromDiameterMichaelisMentenQ75))) %>%
  mutate(species = factor(species, labels = c("Douglas-fir", "western redcedar", "western hemlock", "red alder", "bigleaf maple", "Oregon myrtle", "other species"),  levels = c("PSME", "THPL", "TSHE", "ALRU2", "ACMA3", "UMCA", "other")),
         iqr = q75 - q25)

# Figure S4 in HtDia figures.R

ggplot() +
  geom_point(aes(x = DBH, y = TotalHt), psme2016, alpha = 0.1, color = "grey25", shape = 16) +
  geom_line(aes(x = psme2016$DBH, y = predict(psmeHeightFromDiameterSharmaPartonQ25), color = "q25", group = psme2016$isPlantation, linetype = psme2016$isPlantation), alpha = 0.5) +
  geom_line(aes(x = psme2016$DBH, y = predict(psmeHeightFromDiameterSharmaPartonQ75), color = "q75", group = psme2016$isPlantation, linetype = psme2016$isPlantation), alpha = 0.5) +
  annotate("text", x = 0, y = 83, label = "a) Douglas-fir", hjust = 0, size = 3.5) +
  coord_cartesian(xlim = c(0, 250)) +
  labs(x = "DBH, cm", y = "height of unbroken stem, m", color = NULL, linetype = NULL) +
  scale_color_discrete(breaks = c("q25", "q75"), labels = c("lower quartile", "upper quartile")) +
  scale_linetype_manual(breaks = c(FALSE, TRUE), labels = c("natural regeneration", "plantation"), values = c("solid", "dashed")) +
  theme(legend.justification = c(0, 1), legend.position = "none") +
ggplot() +
  geom_point(aes(x = DBH, y = TotalHt), alru2016, alpha = 0.1, color = "grey25", shape = 16) +
  geom_line(aes(x = alru2016$DBH, y = predict(alruHeightFromDiameterMichaelisMentenQ25), color = "q25", group = alru2016$isPlantation, linetype = alru2016$isPlantation)) +
  geom_line(aes(x = alru2016$DBH, y = predict(alruHeightFromDiameterMichaelisMentenQ75), color = "q75", group = alru2016$isPlantation, linetype = alru2016$isPlantation)) +
  #geom_line(aes(x = alru2016$DBH, y = predict(alruHeightFromDiameterSharmaPartonQ25), color = "q25", group = alru2016$isPlantation, linetype = alru2016$isPlantation), alpha = 0.5) +
  #geom_line(aes(x = alru2016$DBH, y = predict(alruHeightFromDiameterSharmaPartonQ75), color = "q75", group = alru2016$isPlantation, linetype = alru2016$isPlantation), alpha = 0.5) +
  annotate("text", x = 0, y = 83, label = "b) red alder", hjust = 0, size = 3.5) +
  coord_cartesian(xlim = c(0, 120)) +
  labs(x = "DBH, cm", y = "height of unbroken stem, m", color = NULL, linetype = NULL) +
  scale_color_discrete(breaks = c("q25", "q75"), labels = c("lower quartile", "upper quartile")) +
  scale_linetype_manual(breaks = c(FALSE, TRUE), labels = c("natural regeneration", "plantation"), values = c("solid", "dashed")) +
  theme(legend.justification = c(1, 1), legend.position = c(1, 0.9)) +
plot_annotation(theme = theme(plot.margin = margin(1, 1, 1, 1, "pt")))
plot_layout(nrow = 2, widths = c(250, 150))


## diameter interquartile range
psmeDiameterFromHeightRuarkQ25 = nlrq(DBH ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation) * exp((b2 + b2p * isPlantation) * (TotalHt - 1.37)), psme2016, start = list(a1 = 2.67, b1 = 0.813, b1p = -0.126, b2 = 0.0067, b2p = 0.0096), tau = 0.25)
psmeDiameterFromHeightRuarkQ75 = nlrq(DBH ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation) * exp((b2 + b2p * isPlantation) * (TotalHt - 1.37)), psme2016, start = list(a1 = 2.67, b1 = 0.813, b1p = -0.126, b2 = 0.0067, b2p = 0.0096), tau = 0.75)
alruDiameterFromHeightRuarkQ25 = nlrq(DBH ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation) * exp((b2 + b2p * isPlantation) * (TotalHt - 1.37)), alru2016, start = list(a1 = 1.35, b1 = 1.37, b1p = -0.24, b2 = -0.033, b2p = 0.022), tau = 0.25)
alruDiameterFromHeightRuarkQ75 = nlrq(DBH ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation) * exp((b2 + b2p * isPlantation) * (TotalHt - 1.37)), alru2016, start = list(a1 = 1.35, b1 = 1.37, b1p = -0.24, b2 = -0.033, b2p = 0.022), tau = 0.75)
tsheDiameterFromHeightRuarkQ25 = nlrq(DBH ~ a1*(TotalHt - 1.37)^b1 * exp(b2 * (TotalHt - 1.37)), tshe2016, start = list(a1 = 2.31, b1 = 0.818, b2 = 0.010), tau = 0.25)
tsheDiameterFromHeightRuarkQ75 = nlrq(DBH ~ a1*(TotalHt - 1.37)^b1 * exp(b2 * (TotalHt - 1.37)), tshe2016, start = list(a1 = 2.31, b1 = 0.818, b2 = 0.010), tau = 0.75)
acmaDiameterFromHeightRuarkQ25 = nlrq(DBH ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation) * exp((b2 + b2p * isPlantation) * (TotalHt - 1.37)), acma2016, start = list(a1 = 1.20, b1 = 1.52, b1p = -0.32, b2 = -0.038, b2p = 0.037), tau = 0.25)
acmaDiameterFromHeightRuarkQ75 = nlrq(DBH ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation) * exp((b2 + b2p * isPlantation) * (TotalHt - 1.37)), acma2016, start = list(a1 = 1.20, b1 = 1.52, b1p = -0.32, b2 = -0.038, b2p = 0.037), tau = 0.75)
umcaDiameterFromHeightRuarkQ25 = nlrq(DBH ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation) * exp((b2 + b2p * isPlantation) * (TotalHt - 1.37)), umca2016, start = list(a1 = 2.48, b1 = 1.14, b1p = -0.57, b2 = -0.019, b2p = 0.092), tau = 0.25)
umcaDiameterFromHeightRuarkQ75 = nlrq(DBH ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation) * exp((b2 + b2p * isPlantation) * (TotalHt - 1.37)), umca2016, start = list(a1 = 2.48, b1 = 1.14, b1p = -0.57, b2 = -0.019, b2p = 0.092), tau = 0.75)
thplDiameterFromHeightRuarkQ25 = nlrq(DBH ~ a1*(TotalHt - 1.37)^b1 * exp((b2 + b2p * isPlantation) * (TotalHt - 1.37)), thpl2016, start = list(a1 = 2.12, b1 = 1.01, b2 = 0.0038, b2p = 0.0025), tau = 0.25)
thplDiameterFromHeightRuarkQ75 = nlrq(DBH ~ a1*(TotalHt - 1.37)^b1 * exp((b2 + b2p * isPlantation) * (TotalHt - 1.37)), thpl2016, start = list(a1 = 2.12, b1 = 1.01, b2 = 0.0038, b2p = 0.0025), tau = 0.75)
otherDiameterFromHeightRuarkQ25 = nlrq(DBH ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation) * exp((b2 + b2p * isPlantation) * (TotalHt - 1.37)), other2016, start = list(a1 = 2.54, b1 = 0.56, b1p = -0.28, b2 = 0.040, b2p = 0.043), tau = 0.25)
otherDiameterFromHeightRuarkQ75 = nlrq(DBH ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation) * exp((b2 + b2p * isPlantation) * (TotalHt - 1.37)), other2016, start = list(a1 = 2.54, b1 = 0.56, b1p = -0.28, b2 = 0.040, b2p = 0.043), tau = 0.75)


diameterIqr = bind_rows(tibble(species = "PSME", name = "Ruark", fitting = "nlrq", TotalHt = psme2016$TotalHt, isPlantation = psme2016$isPlantation, q25 = predict(psmeDiameterFromHeightRuarkQ25), q75 = predict(psmeDiameterFromHeightRuarkQ75)),
                        tibble(species = "ALRU2", name = "Ruark", fitting = "nlrq", TotalHt = alru2016$TotalHt, isPlantation = alru2016$isPlantation, q25 = predict(alruDiameterFromHeightRuarkQ25), q75 = predict(alruDiameterFromHeightRuarkQ75)),
                        tibble(species = "TSHE", name = "Ruark", fitting = "nlrq", TotalHt = tshe2016$TotalHt, isPlantation = tshe2016$isPlantation, q25 = predict(tsheDiameterFromHeightRuarkQ25), q75 = predict(tsheDiameterFromHeightRuarkQ75)),
                        tibble(species = "ACMA3", name = "Ruark", fitting = "nlrq", TotalHt = acma2016$TotalHt, isPlantation = acma2016$isPlantation, q25 = predict(acmaDiameterFromHeightRuarkQ25), q75 = predict(acmaDiameterFromHeightRuarkQ75)),
                        tibble(species = "UMCA", name = "Ruark", fitting = "nlrq", TotalHt = umca2016$TotalHt, isPlantation = umca2016$isPlantation, q25 = predict(umcaDiameterFromHeightRuarkQ25), q75 = predict(umcaDiameterFromHeightRuarkQ75)),
                        tibble(species = "THPL", name = "Ruark", fitting = "nlrq", TotalHt = thpl2016$TotalHt, isPlantation = thpl2016$isPlantation, q25 = predict(thplDiameterFromHeightRuarkQ25), q75 = predict(thplDiameterFromHeightRuarkQ75)),
                        tibble(species = "other", name = "Ruark", fitting = "nlrq", TotalHt = other2016$TotalHt, isPlantation = other2016$isPlantation, q25 = predict(otherDiameterFromHeightRuarkQ25), q75 = predict(otherDiameterFromHeightRuarkQ75))) %>%
  mutate(species = factor(species, labels = c("Douglas-fir", "western redcedar", "western hemlock", "red alder", "bigleaf maple", "Oregon myrtle", "other species"),  levels = c("PSME", "THPL", "TSHE", "ALRU2", "ACMA3", "UMCA", "other")),
         iqr = q75 - q25)

# Figure S5 in HtDia figures.R

ggplot() +
  geom_point(aes(x = DBH, y = TotalHt), psme2016, alpha = 0.1, color = "grey25", shape = 16) +
  geom_line(aes(x = predict(psmeDiameterFromHeightRuarkQ25), y = psme2016$TotalHt, color = "q25", group = psme2016$isPlantation, linetype = psme2016$isPlantation), alpha = 0.5) +
  geom_line(aes(x = predict(psmeDiameterFromHeightRuarkQ75), y = psme2016$TotalHt, color = "q75", group = psme2016$isPlantation, linetype = psme2016$isPlantation), alpha = 0.5) +
  annotate("text", x = 0, y = 83, label = "a) Douglas-fir", hjust = 0, size = 3.5) +
  coord_cartesian(xlim = c(0, 250)) +
  labs(x = "DBH, cm", y = "height of unbroken stem, m", color = NULL, linetype = NULL) +
  scale_color_discrete(breaks = c("q25", "q75"), labels = c("lower quartile", "upper quartile")) +
  scale_linetype_manual(breaks = c(FALSE, TRUE), labels = c("natural regeneration", "plantation"), values = c("solid", "dashed")) +
  theme(legend.justification = c(0, 1), legend.position = "none") +
ggplot() +
  geom_point(aes(x = DBH, y = TotalHt), alru2016, alpha = 0.1, color = "grey25", shape = 16) +
  geom_line(aes(x = predict(alruDiameterFromHeightRuarkQ25), y = alru2016$TotalHt, color = "q25", group = alru2016$isPlantation, linetype = alru2016$isPlantation)) +
  geom_line(aes(x = predict(alruDiameterFromHeightRuarkQ75), y = alru2016$TotalHt, color = "q75", group = alru2016$isPlantation, linetype = alru2016$isPlantation)) +
  annotate("text", x = 0, y = 83, label = "b) red alder", hjust = 0, size = 3.5) +
  coord_cartesian(xlim = c(0, 120)) +
  labs(x = "DBH, cm", y = "height of unbroken stem, m", color = NULL, linetype = NULL) +
  scale_color_discrete(breaks = c("q25", "q75"), labels = c("lower quartile", "upper quartile")) +
  scale_linetype_manual(breaks = c(FALSE, TRUE), labels = c("natural regeneration", "plantation"), values = c("solid", "dashed")) +
  theme(legend.justification = c(1, 1), legend.position = c(1, 0.9)) +
plot_annotation(theme = theme(plot.margin = margin(1, 1, 1, 1, "pt")))
plot_layout(nrow = 2, widths = c(250, 150))


## direct fitting of height residuals
psmeHeightChapmanRichardsResidualPower = nlrob(residual ~ (a1 + a1p * isPlantation) * DBH^(b1 + b1p * isPlantation), tibble(DBH = psme2016$DBH, isPlantation = psme2016$isPlantation, residual = abs(residuals(psmeHeightFromDiameterChapmanRichards))), start = list(a1 = 1, a1p = 0, b1 = 1, b1p = 0))
alruHeightChapmanRichardsResidualPower = nlrob(residual ~ a1*DBH^(b1 + b1p * isPlantation), tibble(DBH = alru2016$DBH, isPlantation = alru2016$isPlantation, residual = abs(residuals(alruHeightFromDiameterChapmanRichards))), start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p, b1p not mutually significant
tsheHeightChapmanRichardsResidualPower = nlrob(residual ~ a1*DBH^b1, tibble(DBH = tshe2016$DBH, isPlantation = tshe2016$isPlantation, residual = abs(residuals(tsheHeightFromDiameterChapmanRichards))), start = list(a1 = 1, b1 = 1)) # a1p, b1p not significant
acmaHeightChapmanRichardsResidualPower = nlrob(residual ~ a1*DBH^b1, tibble(DBH = acma2016$DBH, isPlantation = acma2016$isPlantation, residual = abs(residuals(acmaHeightFromDiameterChapmanRichards))), start = list(a1 = 1, b1 = 1)) # a1p, b1p not significant
umcaHeightChapmanRichardsResidualPower = nlrob(residual ~ a1*DBH^b1, tibble(DBH = umca2016$DBH, isPlantation = umca2016$isPlantation, residual = abs(residuals(umcaHeightFromDiameterChapmanRichards))), start = list(a1 = 1, b1 = 1)) # a1p, b1p not significant
thplHeightChapmanRichardsResidualPower = nlrob(residual ~ a1*DBH^b1, tibble(DBH = thpl2016$DBH, isPlantation = thpl2016$isPlantation, residual = abs(residuals(thplHeightFromDiameterChapmanRichards))), start = list(a1 = 1, b1 = 1)) # a1p, b1p not significant
otherHeightChapmanRichardsResidualPower = nlrob(residual ~ (a1 + a1p * isPlantation) * DBH^(b1 + b1p * isPlantation), tibble(DBH = other2016$DBH, isPlantation = other2016$isPlantation, residual = abs(residuals(otherHeightFromDiameterChapmanRichards))), start = list(a1 = 1, a1p = 0, b1 = 1, b1p = 0))

psmeHeightMichaelisMentenResidualPower = nlrob(residual ~ (a1 + a1p * isPlantation) * DBH^(b1 + b1p * isPlantation), tibble(DBH = psme2016$DBH, isPlantation = psme2016$isPlantation, residual = abs(residuals(psmeHeightFromDiameterMichaelisMenten))), start = list(a1 = 1, a1p = 0, b1 = 1, b1p = 0))
alruHeightMichaelisMentenResidualPower = nlrob(residual ~ a1*DBH^(b1 + b1p * isPlantation), tibble(DBH = alru2016$DBH, isPlantation = alru2016$isPlantation, residual = abs(residuals(alruHeightFromDiameterMichaelisMenten))), start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p, b1p not mutually significant
tsheHeightMichaelisMentenResidualPower = nlrob(residual ~ a1*DBH^b1, tibble(DBH = tshe2016$DBH, isPlantation = tshe2016$isPlantation, residual = abs(residuals(tsheHeightFromDiameterMichaelisMenten))), start = list(a1 = 1, b1 = 1)) # a1p, b1p not significant
acmaHeightMichaelisMentenResidualPower = nlrob(residual ~ a1*DBH^b1, tibble(DBH = acma2016$DBH, isPlantation = acma2016$isPlantation, residual = abs(residuals(acmaHeightFromDiameterMichaelisMenten))), start = list(a1 = 1, b1 = 1)) # a1p, b1p not significant
umcaHeightMichaelisMentenResidualPower = nlrob(residual ~ a1*DBH^b1, tibble(DBH = umca2016$DBH, isPlantation = umca2016$isPlantation, residual = abs(residuals(umcaHeightFromDiameterMichaelisMenten))), start = list(a1 = 1, b1 = 1)) # a1p, b1p not significant
thplHeightMichaelisMentenResidualPower = nlrob(residual ~ a1*DBH^b1, tibble(DBH = thpl2016$DBH, isPlantation = thpl2016$isPlantation, residual = abs(residuals(thplHeightFromDiameterMichaelisMenten))), start = list(a1 = 1, b1 = 1)) # a1p, b1p not significant
otherHeightMichaelisMentenResidualPower = nlrob(residual ~ (a1 + a1p * isPlantation) * DBH^(b1 + b1p * isPlantation), tibble(DBH = other2016$DBH, isPlantation = other2016$isPlantation, residual = abs(residuals(otherHeightFromDiameterMichaelisMenten))), start = list(a1 = 1, a1p = 0, b1 = 1, b1p = 0))

psmeHeightSharmaPartonResidualPower = nlrob(residual ~ (a1 + a1p * isPlantation) * DBH^(b1 + b1p * isPlantation), tibble(DBH = psme2016$DBH, isPlantation = psme2016$isPlantation, residual = abs(residuals(psmeHeightFromDiameterSharmaParton))), start = list(a1 = 1, a1p = 0, b1 = 1, b1p = 0))
alruHeightSharmaPartonResidualPower = nlrob(residual ~ a1*DBH^(b1 + b1p * isPlantation), tibble(DBH = alru2016$DBH, isPlantation = alru2016$isPlantation, residual = abs(residuals(alruHeightFromDiameterSharmaParton))), start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p, b1p not mutually significant
tsheHeightSharmaPartonResidualPower = nlrob(residual ~ a1*DBH^b1, tibble(DBH = tshe2016$DBH, isPlantation = tshe2016$isPlantation, residual = abs(residuals(tsheHeightFromDiameterSharmaParton))), start = list(a1 = 1, b1 = 1)) # a1p, b1p not significant
acmaHeightSharmaPartonResidualPower = nlrob(residual ~ a1*DBH^b1, tibble(DBH = acma2016$DBH, isPlantation = acma2016$isPlantation, residual = abs(residuals(acmaHeightFromDiameterSharmaParton))), start = list(a1 = 1, b1 = 1)) # a1p, b1p not significant
umcaHeightSharmaPartonResidualPower = nlrob(residual ~ a1*DBH^b1, tibble(DBH = umca2016$DBH, isPlantation = umca2016$isPlantation, residual = abs(residuals(umcaHeightFromDiameterSharmaParton))), start = list(a1 = 1, b1 = 1)) # a1p, b1p not significant
thplHeightSharmaPartonResidualPower = nlrob(residual ~ a1*DBH^b1, tibble(DBH = thpl2016$DBH, isPlantation = thpl2016$isPlantation, residual = abs(residuals(thplHeightFromDiameterSharmaParton))), start = list(a1 = 1, b1 = 1)) # a1p, b1p not significant
otherHeightSharmaPartonResidualPower = nlrob(residual ~ (a1 + a1p * isPlantation) * DBH^(b1 + b1p * isPlantation), tibble(DBH = other2016$DBH, isPlantation = other2016$isPlantation, residual = abs(residuals(otherHeightFromDiameterSharmaParton))), start = list(a1 = 1, a1p = 0, b1 = 1, b1p = 0))

psmeHeightSharmaZhangResidualPower = nlrob(residual ~ a1*DBH^(b1 + b1p * isPlantation), tibble(DBH = psme2016$DBH, isPlantation = psme2016$isPlantation, residual = abs(residuals(psmeHeightFromDiameterSharmaZhang))), start = list(a1 = 1, b1 = 1, b1p = 0)) # singular gradient with a1p
alruHeightSharmaZhangResidualPower = nlrob(residual ~ a1*DBH^(b1 + b1p * isPlantation), tibble(DBH = alru2016$DBH, isPlantation = alru2016$isPlantation, residual = abs(residuals(alruHeightFromDiameterSharmaZhang))), start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p, b1p not mutually significant
tsheHeightSharmaZhangResidualPower = nlrob(residual ~ a1*DBH^b1, tibble(DBH = tshe2016$DBH, isPlantation = tshe2016$isPlantation, residual = abs(residuals(tsheHeightFromDiameterSharmaZhang))), start = list(a1 = 1, b1 = 1)) # a1p, b1p not significant
acmaHeightSharmaZhangResidualPower = nlrob(residual ~ a1*DBH^b1, tibble(DBH = acma2016$DBH, isPlantation = acma2016$isPlantation, residual = abs(residuals(acmaHeightFromDiameterSharmaZhang))), start = list(a1 = 1, b1 = 1)) # a1p, b1p not significant
umcaHeightSharmaZhangResidualPower = nlrob(residual ~ a1*DBH^b1, tibble(DBH = umca2016$DBH, isPlantation = umca2016$isPlantation, residual = abs(residuals(umcaHeightFromDiameterSharmaZhang))), start = list(a1 = 1, b1 = 1)) # a1p, b1p not significant
thplHeightSharmaZhangResidualPower = nlrob(residual ~ a1*DBH^b1, tibble(DBH = thpl2016$DBH, isPlantation = thpl2016$isPlantation, residual = abs(residuals(thplHeightFromDiameterSharmaZhang))), start = list(a1 = 1, b1 = 1)) # a1p, b1p not significant
otherHeightSharmaZhangResidualPower = nlrob(residual ~ (a1 + a1p * isPlantation) * DBH^(b1 + b1p * isPlantation), tibble(DBH = other2016$DBH, isPlantation = other2016$isPlantation, residual = abs(residuals(otherHeightFromDiameterSharmaZhang))), maxit = 50, start = list(a1 = 1, a1p = 0, b1 = 1, b1p = 0))

psmeHeightChapmanRichardsResidualPower$confint = confint_nlrob(psmeHeightChapmanRichardsResidualPower, level = 0.99, weights = rep(1, psmeHeightChapmanRichardsResidualPower$nobs))
alruHeightChapmanRichardsResidualPower$confint = confint_nlrob(alruHeightChapmanRichardsResidualPower, level = 0.99, weights = rep(1, alruHeightChapmanRichardsResidualPower$nobs))
tsheHeightChapmanRichardsResidualPower$confint = confint_nlrob(tsheHeightChapmanRichardsResidualPower, level = 0.99, weights = rep(1, tsheHeightChapmanRichardsResidualPower$nobs))
acmaHeightChapmanRichardsResidualPower$confint = confint_nlrob(acmaHeightChapmanRichardsResidualPower, level = 0.99, weights = rep(1, acmaHeightChapmanRichardsResidualPower$nobs))
umcaHeightChapmanRichardsResidualPower$confint = confint_nlrob(umcaHeightChapmanRichardsResidualPower, level = 0.99, weights = rep(1, umcaHeightChapmanRichardsResidualPower$nobs))
thplHeightChapmanRichardsResidualPower$confint = confint_nlrob(thplHeightChapmanRichardsResidualPower, level = 0.99, weights = rep(1, thplHeightChapmanRichardsResidualPower$nobs))
otherHeightChapmanRichardsResidualPower$confint = confint_nlrob(otherHeightChapmanRichardsResidualPower, level = 0.99, weights = rep(1, otherHeightChapmanRichardsResidualPower$nobs))

psmeHeightMichaelisMentenResidualPower$confint = confint_nlrob(psmeHeightMichaelisMentenResidualPower, level = 0.99, weights = rep(1, psmeHeightMichaelisMentenResidualPower$nobs))
alruHeightMichaelisMentenResidualPower$confint = confint_nlrob(alruHeightMichaelisMentenResidualPower, level = 0.99, weights = rep(1, alruHeightMichaelisMentenResidualPower$nobs))
tsheHeightMichaelisMentenResidualPower$confint = confint_nlrob(tsheHeightMichaelisMentenResidualPower, level = 0.99, weights = rep(1, tsheHeightMichaelisMentenResidualPower$nobs))
acmaHeightMichaelisMentenResidualPower$confint = confint_nlrob(acmaHeightMichaelisMentenResidualPower, level = 0.99, weights = rep(1, acmaHeightMichaelisMentenResidualPower$nobs))
umcaHeightMichaelisMentenResidualPower$confint = confint_nlrob(umcaHeightMichaelisMentenResidualPower, level = 0.99, weights = rep(1, umcaHeightMichaelisMentenResidualPower$nobs))
thplHeightMichaelisMentenResidualPower$confint = confint_nlrob(thplHeightMichaelisMentenResidualPower, level = 0.99, weights = rep(1, thplHeightMichaelisMentenResidualPower$nobs))
otherHeightMichaelisMentenResidualPower$confint = confint_nlrob(otherHeightMichaelisMentenResidualPower, level = 0.99, weights = rep(1, otherHeightMichaelisMentenResidualPower$nobs))

psmeHeightSharmaPartonResidualPower$confint = confint_nlrob(psmeHeightSharmaPartonResidualPower, level = 0.99, weights = rep(1, psmeHeightSharmaPartonResidualPower$nobs))
alruHeightSharmaPartonResidualPower$confint = confint_nlrob(alruHeightSharmaPartonResidualPower, level = 0.99, weights = rep(1, alruHeightSharmaPartonResidualPower$nobs))
tsheHeightSharmaPartonResidualPower$confint = confint_nlrob(tsheHeightSharmaPartonResidualPower, level = 0.99, weights = rep(1, tsheHeightSharmaPartonResidualPower$nobs))
acmaHeightSharmaPartonResidualPower$confint = confint_nlrob(acmaHeightSharmaPartonResidualPower, level = 0.99, weights = rep(1, acmaHeightSharmaPartonResidualPower$nobs))
umcaHeightSharmaPartonResidualPower$confint = confint_nlrob(umcaHeightSharmaPartonResidualPower, level = 0.99, weights = rep(1, umcaHeightSharmaPartonResidualPower$nobs))
thplHeightSharmaPartonResidualPower$confint = confint_nlrob(thplHeightSharmaPartonResidualPower, level = 0.99, weights = rep(1, thplHeightSharmaPartonResidualPower$nobs))
otherHeightSharmaPartonResidualPower$confint = confint_nlrob(otherHeightSharmaPartonResidualPower, level = 0.99, weights = rep(1, otherHeightSharmaPartonResidualPower$nobs))

psmeHeightSharmaZhangResidualPower$confint = confint_nlrob(psmeHeightSharmaZhangResidualPower, level = 0.99, weights = rep(1, psmeHeightSharmaZhangResidualPower$nobs))
alruHeightSharmaZhangResidualPower$confint = confint_nlrob(alruHeightSharmaZhangResidualPower, level = 0.99, weights = rep(1, alruHeightSharmaZhangResidualPower$nobs))
tsheHeightSharmaZhangResidualPower$confint = confint_nlrob(tsheHeightSharmaZhangResidualPower, level = 0.99, weights = rep(1, tsheHeightSharmaZhangResidualPower$nobs))
acmaHeightSharmaZhangResidualPower$confint = confint_nlrob(acmaHeightSharmaZhangResidualPower, level = 0.99, weights = rep(1, acmaHeightSharmaZhangResidualPower$nobs))
umcaHeightSharmaZhangResidualPower$confint = confint_nlrob(umcaHeightSharmaZhangResidualPower, level = 0.99, weights = rep(1, umcaHeightSharmaZhangResidualPower$nobs))
thplHeightSharmaZhangResidualPower$confint = confint_nlrob(thplHeightSharmaZhangResidualPower, level = 0.99, weights = rep(1, thplHeightSharmaZhangResidualPower$nobs))
otherHeightSharmaZhangResidualPower$confint = confint_nlrob(otherHeightSharmaZhangResidualPower, level = 0.99, weights = rep(1, otherHeightSharmaZhangResidualPower$nobs))

psmeHeightMichaelisMentenResidualConstPower = nlrob(residual ~ a0 + (a1 + a1p * isPlantation) * DBH^(b1 + b1p * isPlantation), tibble(DBH = psme2016$DBH, isPlantation = psme2016$isPlantation, residual = abs(residuals(psmeHeightFromDiameterMichaelisMenten))), start = list(a0 = 0, a1 = 2.1, a1p = -1.6, b1 = 0.17, b1p = 0.34)) # singular gradient
#alruHeightMichaelisMentenResidualConstPower = nlrob(residual ~ a0 + a1*DBH^(b1 + b1p * isPlantation), tibble(DBH = alru2016$DBH, isPlantation = alru2016$isPlantation, residual = abs(residuals(alruHeightFromDiameterMichaelisMenten))), start = list(a0 = 0, a1 = 0.94, b1 = 0.38, b1p = -0.04), control = nls.control(maxiter = 500)) # step factor
tsheHeightMichaelisMentenResidualConstPower = nlrob(residual ~ a0 + a1*DBH^b1, tibble(DBH = tshe2016$DBH, isPlantation = tshe2016$isPlantation, residual = abs(residuals(tsheHeightFromDiameterMichaelisMenten))), start = list(a0 = 0, a1 = 1, b1 = 1))
acmaHeightMichaelisMentenResidualConstPower = nlrob(residual ~ a0 + a1*DBH^b1, tibble(DBH = acma2016$DBH, isPlantation = acma2016$isPlantation, residual = abs(residuals(acmaHeightFromDiameterMichaelisMenten))), start = list(a0 = 0, a1 = 1, b1 = 1))
umcaHeightMichaelisMentenResidualConstPower = nlrob(residual ~ a0 + a1*DBH^b1, tibble(DBH = umca2016$DBH, isPlantation = umca2016$isPlantation, residual = abs(residuals(umcaHeightFromDiameterMichaelisMenten))), start = list(a0 = 0, a1 = 1, b1 = 1))
thplHeightMichaelisMentenResidualConstPower = nlrob(residual ~ a0 + a1*DBH^b1, tibble(DBH = thpl2016$DBH, isPlantation = thpl2016$isPlantation, residual = abs(residuals(thplHeightFromDiameterMichaelisMenten))), start = list(a0 = 0, a1 = 1, b1 = 1))
otherHeightMichaelisMentenResidualConstPower = nlrob(residual ~ a0 + (a1 + a1p * isPlantation) * DBH^(b1 + b1p * isPlantation), tibble(DBH = other2016$DBH, isPlantation = other2016$isPlantation, residual = abs(residuals(otherHeightFromDiameterMichaelisMenten))), start = list(a0 = 0, a1 = 1, a1p = 0, b1 = 1, b1p = 0))

tribble(~species, ~name, ~mae, ~aic,
        "PSME", "power", mean(abs(residuals(psmeHeightMichaelisMentenResidualPower))), AIC(psmeHeightMichaelisMentenResidualPower),
        "PSME", "const+power", mean(abs(residuals(psmeHeightMichaelisMentenResidualConstPower))), AIC(psmeHeightMichaelisMentenResidualConstPower),
        "TSHE", "power", mean(abs(residuals(tsheHeightMichaelisMentenResidualPower))), AIC(tsheHeightMichaelisMentenResidualPower),
        "TSHE", "const+power", mean(abs(residuals(tsheHeightMichaelisMentenResidualConstPower))), AIC(tsheHeightMichaelisMentenResidualConstPower),
        "ACMA", "power", mean(abs(residuals(acmaHeightMichaelisMentenResidualPower))), AIC(acmaHeightMichaelisMentenResidualPower),
        "ACMA", "const+power", mean(abs(residuals(acmaHeightMichaelisMentenResidualConstPower))), AIC(acmaHeightMichaelisMentenResidualConstPower),
        "UMCA", "power", mean(abs(residuals(umcaHeightMichaelisMentenResidualPower))), AIC(umcaHeightMichaelisMentenResidualPower),
        "UMCA", "const+power", mean(abs(residuals(umcaHeightMichaelisMentenResidualConstPower))), AIC(umcaHeightMichaelisMentenResidualConstPower),
        "THPL", "power", mean(abs(residuals(thplHeightMichaelisMentenResidualPower))), AIC(thplHeightMichaelisMentenResidualPower),
        "THPL", "const+power", mean(abs(residuals(thplHeightMichaelisMentenResidualConstPower))), AIC(thplHeightMichaelisMentenResidualConstPower),
        "other", "power", mean(abs(residuals(otherHeightMichaelisMentenResidualPower))), AIC(otherHeightMichaelisMentenResidualPower),
        "other", "const+power", mean(abs(residuals(otherHeightMichaelisMentenResidualConstPower))), AIC(otherHeightMichaelisMentenResidualConstPower))


## direct fitting of diameter residuals
psmeDiameterGslNlsResidualConstPower = gsl_nls(residual ~ a0 + a1*(TotalHt - 1.37)^b1, tibble(TotalHt = psme2016$TotalHt, isPlantation = psme2016$isPlantation, residual = abs(residuals(psmeDiameterFromHeightRuark))), start = list(a0 = 0, a1 = 1, b1 = 1), control = gsl_nls_control(maxiter = 250))
psmeDiameterGslNlsResidualPower = gsl_nls(residual ~ a1*(TotalHt - 1.37)^b1, tibble(TotalHt = psme2016$TotalHt, isPlantation = psme2016$isPlantation, residual = abs(residuals(psmeDiameterFromHeightRuark))), start = list(a1 = 1, b1 = 1))
psmeDiameterResidualLm01 = lm(residual ~ 0 + I(TotalHt - 1.37), tibble(TotalHt = psme2016$TotalHt, isPlantation = psme2016$isPlantation, residual = abs(residuals(psmeDiameterFromHeightRuark))))
psmeDiameterResidualLm0.5 = lm(residual ~ I(sqrt(TotalHt - 1.37)), tibble(TotalHt = psme2016$TotalHt, isPlantation = psme2016$isPlantation, residual = abs(residuals(psmeDiameterFromHeightRuark))))
psmeDiameterResidualLm1 = lm(residual ~ I(TotalHt - 1.37), tibble(TotalHt = psme2016$TotalHt, isPlantation = psme2016$isPlantation, residual = abs(residuals(psmeDiameterFromHeightRuark))))
psmeDiameterResidualLm2 = lm(residual ~ I(TotalHt - 1.37) + I((TotalHt - 1.37)^2), tibble(TotalHt = psme2016$TotalHt, isPlantation = psme2016$isPlantation, residual = abs(residuals(psmeDiameterFromHeightRuark))))
psmeDiameterResidualLm3 = lm(residual ~ I(TotalHt - 1.37) + I((TotalHt - 1.37)^2) + I((TotalHt - 1.37)^3), tibble(TotalHt = psme2016$TotalHt, isPlantation = psme2016$isPlantation, residual = abs(residuals(psmeDiameterFromHeightRuark))))
psmeDiameterRuarkResidualConstPower = gsl_nls(residual ~ a0 + a1*(TotalHt - 1.37)^b1, tibble(TotalHt = psme2016$TotalHt, isPlantation = psme2016$isPlantation, residual = abs(residuals(psmeDiameterFromHeightRuark))), start = list(a0 = 0, a1 = 1, b1 = 1), control = nls.control(maxiter = 250)) # parameter evaporation
psmeDiameterRuarkResidualPower = nlrob(residual ~ a1*(TotalHt - 1.37)^b1, tibble(TotalHt = psme2016$TotalHt, isPlantation = psme2016$isPlantation, residual = abs(residuals(psmeDiameterFromHeightRuark))), start = list(a1 = 1, b1 = 1))
psmeDiameterRuarkResidualPower = nlrob(residual ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = psme2016$TotalHt, isPlantation = psme2016$isPlantation, residual = abs(residuals(psmeDiameterFromHeightRuark))), start = list(a1 = 1, b1 = 1, b1p = 0)) # NaN-inf with a1p
psmeDiameterRuarkResidualPower$confint = confint_nlrob(psmeDiameterRuarkResidualPower, level = 0.99, weights = rep(1, psmeDiameterRuarkResidualPower$nobs))

tribble(~name, ~mae, ~aic,
        "gsl_nls const", mean(abs(residuals(psmeDiameterGslNlsResidualConstPower))), AIC(psmeDiameterGslNlsResidualConstPower),
        "gsl_nls", mean(abs(residuals(psmeDiameterGslNlsResidualPower))), AIC(psmeDiameterGslNlsResidualPower),
        "nlrob const", mean(abs(residuals(psmeDiameterRuarkResidualConstPower))), AIC(psmeDiameterRuarkResidualConstPower),
        "nlrob", mean(abs(residuals(psmeDiameterRuarkResidualPower))), AIC(psmeDiameterRuarkResidualPower),
        "lm01", mean(abs(residuals(psmeDiameterResidualLm01))), AIC(psmeDiameterResidualLm01),
        "lm0.5", mean(abs(residuals(psmeDiameterResidualLm0.5))), AIC(psmeDiameterResidualLm0.5),
        "lm1", mean(abs(residuals(psmeDiameterResidualLm1))), AIC(psmeDiameterResidualLm1),
        "lm2", mean(abs(residuals(psmeDiameterResidualLm2))), AIC(psmeDiameterResidualLm2),
        "lm3", mean(abs(residuals(psmeDiameterResidualLm3))), AIC(psmeDiameterResidualLm3)) %>%
  mutate(deltaAic = aic - min(aic)) %>%
  arrange(desc(deltaAic))

tibble(gsl_nls = mean(abs(residuals(psmeDiameterGslNlsResidualPower))), nlrob = mean(abs(residuals(psmeDiameterRuarkResidualPower))), lm0.5 = mean(abs(psmeDiameterResidualLm0.5$residuals)), lm01 = mean(abs(psmeDiameterResidualLm01$residuals)), lm1 = mean(abs(psmeDiameterResidualLm1$residuals)), lm2 = mean(abs(psmeDiameterResidualLm2$residuals)))

ggplot() +
  geom_segment(aes(x = 1.37, xend = 1.37, y = 0, yend = 130), color = "grey70", linetype = "longdash") +
  geom_point(aes(x = psme2016$TotalHt, y = abs(residuals(psmeDiameterFromHeightRuark))), alpha = 0.1, color = "grey25", shape = 16) +
  geom_smooth(aes(x = psme2016$TotalHt, y = abs(residuals(psmeDiameterFromHeightRuark)), color = "Ruark GAM", fill = "Ruark GAM"), alpha = 0.1, formula = y ~ s(x, k = 10), method = "gam") +
  #geom_line(aes(x = psme2016$TotalHt, y = predict(psmeDiameterGslNlsResidualConstPower), color = "gsl_nls() const", group = psme2016$isPlantation)) +
  geom_line(aes(x = psme2016$TotalHt, y = predict(psmeDiameterGslNlsResidualPower), color = "gsl_nls()", group = psme2016$isPlantation)) +
  #geom_line(aes(x = psme2016$TotalHt, y = predict(psmeDiameterResidualLm01), color = "lm01", group = psme2016$isPlantation)) +
  geom_line(aes(x = psme2016$TotalHt, y = predict(psmeDiameterResidualLm3), color = "lm3", group = psme2016$isPlantation)) +
  #geom_line(aes(x = psme2016$TotalHt, y = predict(psmeDiameterRuarkResidualConstPower), color = "nlrob() const", group = psme2016$isPlantation)) +
  geom_line(aes(x = psme2016$TotalHt, y = predict(psmeDiameterRuarkResidualPower), color = "nlrob()", group = psme2016$isPlantation)) +
  labs(x = "height, m", y = "diameter residual, cm", color = NULL, fill = NULL) +
  theme(legend.justification = c(0, 1), legend.position = c(0.03, 1))


alruDiameterGslNlsResidualConstPower = gsl_nls(residual ~ a0 + a1*(TotalHt - 1.37)^b1, tibble(TotalHt = alru2016$TotalHt, isPlantation = alru2016$isPlantation, residual = abs(residuals(alruDiameterFromHeightRuark))), start = list(a0 = 0, a1 = 1, b1 = 1), control = gsl_nls_control(maxiter = 250))
alruDiameterGslNlsResidualPower = gsl_nls(residual ~ a1*(TotalHt - 1.37)^b1, tibble(TotalHt = alru2016$TotalHt, isPlantation = alru2016$isPlantation, residual = abs(residuals(alruDiameterFromHeightRuark))), start = list(a1 = 1, b1 = 1))
alruDiameterResidualLm01 = lm(residual ~ 0 + I(TotalHt - 1.37), tibble(TotalHt = alru2016$TotalHt, isPlantation = alru2016$isPlantation, residual = abs(residuals(alruDiameterFromHeightRuark))))
alruDiameterResidualLm0.5 = lm(residual ~ I(sqrt(TotalHt - 1.37)), tibble(TotalHt = alru2016$TotalHt, isPlantation = alru2016$isPlantation, residual = abs(residuals(alruDiameterFromHeightRuark))))
alruDiameterResidualLm1 = lm(residual ~ I(TotalHt - 1.37), tibble(TotalHt = alru2016$TotalHt, isPlantation = alru2016$isPlantation, residual = abs(residuals(alruDiameterFromHeightRuark))))
alruDiameterResidualLm2 = lm(residual ~ I(TotalHt - 1.37) + I((TotalHt - 1.37)^2), tibble(TotalHt = alru2016$TotalHt, isPlantation = alru2016$isPlantation, residual = abs(residuals(alruDiameterFromHeightRuark))))
alruDiameterResidualLm3 = lm(residual ~ I(TotalHt - 1.37) + I((TotalHt - 1.37)^2) + I((TotalHt - 1.37)^3), tibble(TotalHt = alru2016$TotalHt, isPlantation = alru2016$isPlantation, residual = abs(residuals(alruDiameterFromHeightRuark))))
alruDiameterRuarkResidualConstPower = gsl_nls(residual ~ a0 + a1*(TotalHt - 1.37)^b1, tibble(TotalHt = alru2016$TotalHt, isPlantation = alru2016$isPlantation, residual = abs(residuals(alruDiameterFromHeightRuark))), start = list(a0 = 0, a1 = 1, b1 = 1), control = nls.control(maxiter = 250)) # parameter evaporation
alruDiameterRuarkResidualPower = nlrob(residual ~ (a1 + a1p * isPlantation) * (TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = alru2016$TotalHt, isPlantation = alru2016$isPlantation, residual = abs(residuals(alruDiameterFromHeightRuark))), start = list(a1 = 1, a1p = 0, b1 = 1, b1p = 0))
alruDiameterRuarkResidualPower$confint = confint_nlrob(alruDiameterRuarkResidualPower, level = 0.99, weights = rep(1, alruDiameterRuarkResidualPower$nobs))

tribble(~name, ~mae, ~aic,
        "gsl_nls const", mean(abs(residuals(alruDiameterGslNlsResidualConstPower))), AIC(alruDiameterGslNlsResidualConstPower),
        "gsl_nls", mean(abs(residuals(alruDiameterGslNlsResidualPower))), AIC(alruDiameterGslNlsResidualPower),
        "nlrob const", mean(abs(residuals(alruDiameterRuarkResidualConstPower))), AIC(alruDiameterRuarkResidualConstPower),
        "nlrob", mean(abs(residuals(alruDiameterRuarkResidualPower))), AIC(alruDiameterRuarkResidualPower),
        "lm01", mean(abs(residuals(alruDiameterResidualLm01))), AIC(alruDiameterResidualLm01),
        "lm0.5", mean(abs(residuals(alruDiameterResidualLm0.5))), AIC(alruDiameterResidualLm0.5),
        "lm1", mean(abs(residuals(alruDiameterResidualLm1))), AIC(alruDiameterResidualLm1),
        "lm2", mean(abs(residuals(alruDiameterResidualLm2))), AIC(alruDiameterResidualLm2),
        "lm3", mean(abs(residuals(alruDiameterResidualLm3))), AIC(alruDiameterResidualLm3)) %>%
  mutate(deltaAic = aic - min(aic)) %>%
  arrange(desc(deltaAic))

tibble(gsl_nls = mean(abs(residuals(alruDiameterGslNlsResidualPower))), nlrob = mean(abs(residuals(alruDiameterRuarkResidualPower))), lm0.5 = mean(abs(alruDiameterResidualLm0.5$residuals)), lm01 = mean(abs(alruDiameterResidualLm01$residuals)), lm1 = mean(abs(alruDiameterResidualLm1$residuals)), lm2 = mean(abs(alruDiameterResidualLm2$residuals)))

ggplot() +
  geom_segment(aes(x = 1.37, xend = 1.37, y = 0, yend = 70), color = "grey70", linetype = "longdash") +
  geom_point(aes(x = alru2016$TotalHt, y = abs(residuals(alruDiameterFromHeightRuark)), color = isPlantation), alpha = 0.1, color = "grey25", shape = 16) +
  geom_smooth(aes(x = alru2016$TotalHt, y = abs(residuals(alruDiameterFromHeightRuark)), color = "Ruark GAM", fill = "Ruark GAM"), alpha = 0.1, formula = y ~ s(x, k = 10), method = "gam") +
  #geom_line(aes(x = alru2016$TotalHt, y = predict(alruDiameterGslNlsResidualConstPower), color = "gsl_nls() const", group = alru2016$isPlantation)) +
  geom_line(aes(x = alru2016$TotalHt, y = predict(alruDiameterGslNlsResidualPower), color = "gsl_nls()", group = alru2016$isPlantation)) +
  #geom_line(aes(x = alru2016$TotalHt, y = predict(alruDiameterResidualLm01), color = "lm01", group = alru2016$isPlantation)) +
  geom_line(aes(x = alru2016$TotalHt, y = predict(alruDiameterResidualLm3), color = "lm3", group = alru2016$isPlantation)) +
  #geom_line(aes(x = alru2016$TotalHt, y = predict(alruDiameterRuarkResidualConstPower), color = "nlrob() const", group = alru2016$isPlantation)) +
  geom_line(aes(x = alru2016$TotalHt, y = predict(alruDiameterRuarkResidualPower), color = "nlrob()", group = alru2016$isPlantation)) +
  labs(x = "height, m", y = "diameter residual, cm", color = NULL, fill = NULL) +
  theme(legend.justification = c(0, 1), legend.position = c(0.03, 1))

psmeDiameterChapmanFormResidualPower = nlrob(residual ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = psme2016$TotalHt, isPlantation = psme2016$isPlantation, residual = abs(residuals(psmeDiameterFromHeightChapmanForm))), start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p not significant
alruDiameterChapmanFormResidualPower = nlrob(residual ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = alru2016$TotalHt, isPlantation = alru2016$isPlantation, residual = abs(residuals(alruDiameterFromHeightChapmanForm))), start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p not significant
tsheDiameterChapmanFormResidualPower = nlrob(residual ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = tshe2016$TotalHt, isPlantation = tshe2016$isPlantation, residual = abs(residuals(tsheDiameterFromHeightChapmanForm))), start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p not significant
acmaDiameterChapmanFormResidualPower = nlrob(residual ~ (a1 + a1p * isPlantation) * (TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = acma2016$TotalHt, isPlantation = acma2016$isPlantation, residual = abs(residuals(acmaDiameterFromHeightChapmanForm))), start = list(a1 = 1, a1p = 0, b1 = 1, b1p = 0))
umcaDiameterChapmanFormResidualPower = nlrob(residual ~ (a1 + a1p * isPlantation) * (TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = umca2016$TotalHt, isPlantation = umca2016$isPlantation, residual = abs(residuals(umcaDiameterFromHeightChapmanForm))), start = list(a1 = 1, a1p = 0, b1 = 1, b1p = 0))
thplDiameterChapmanFormResidualPower = nlrob(residual ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = thpl2016$TotalHt, isPlantation = thpl2016$isPlantation, residual = abs(residuals(thplDiameterFromHeightChapmanForm))), start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p, b1p not mutually significant
otherDiameterChapmanFormResidualPower = nlrob(residual ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = other2016$TotalHt, isPlantation = other2016$isPlantation, residual = abs(residuals(otherDiameterFromHeightChapmanForm))), maxit = 100, start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p not significant

psmeDiameterChapmanRichardsResidualPower = nlrob(residual ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = psme2016$TotalHt, isPlantation = psme2016$isPlantation, residual = abs(residuals(psmeDiameterFromHeightChapmanRichards))), start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p not significant
alruDiameterChapmanRichardsResidualPower = nlrob(residual ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = alru2016$TotalHt, isPlantation = alru2016$isPlantation, residual = abs(residuals(alruDiameterFromHeightChapmanRichards))), start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p not significant
tsheDiameterChapmanRichardsResidualPower = nlrob(residual ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = tshe2016$TotalHt, isPlantation = tshe2016$isPlantation, residual = abs(residuals(tsheDiameterFromHeightChapmanRichards))), start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p not significant
acmaDiameterChapmanRichardsResidualPower = nlrob(residual ~ (a1 + a1p * isPlantation) * (TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = acma2016$TotalHt, isPlantation = acma2016$isPlantation, residual = abs(residuals(acmaDiameterFromHeightChapmanRichards))), start = list(a1 = 1, a1p = 0, b1 = 1, b1p = 0))
umcaDiameterChapmanRichardsResidualPower = nlrob(residual ~ (a1 + a1p * isPlantation) * (TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = umca2016$TotalHt, isPlantation = umca2016$isPlantation, residual = abs(residuals(umcaDiameterFromHeightChapmanRichards))), start = list(a1 = 1, a1p = 0, b1 = 1, b1p = 0))
thplDiameterChapmanRichardsResidualPower = nlrob(residual ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = thpl2016$TotalHt, isPlantation = thpl2016$isPlantation, residual = abs(residuals(thplDiameterFromHeightChapmanRichards))), start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p, b1p not mutually significant
otherDiameterChapmanRichardsResidualPower = nlrob(residual ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = other2016$TotalHt, isPlantation = other2016$isPlantation, residual = abs(residuals(otherDiameterFromHeightChapmanRichards))), maxit = 100, start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p not significant

tsheDiameterRuarkResidualPower = nlrob(residual ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = tshe2016$TotalHt, isPlantation = tshe2016$isPlantation, residual = abs(residuals(tsheDiameterFromHeightRuark))), start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p not significant
acmaDiameterRuarkResidualPower = nlrob(residual ~ (a1 + a1p * isPlantation) * (TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = acma2016$TotalHt, isPlantation = acma2016$isPlantation, residual = abs(residuals(acmaDiameterFromHeightRuark))), start = list(a1 = 1, a1p = 0, b1 = 1, b1p = 0))
umcaDiameterRuarkResidualPower = nlrob(residual ~ (a1 + a1p * isPlantation) * (TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = umca2016$TotalHt, isPlantation = umca2016$isPlantation, residual = abs(residuals(umcaDiameterFromHeightRuark))), start = list(a1 = 1, a1p = 0, b1 = 1, b1p = 0))
thplDiameterRuarkResidualPower = nlrob(residual ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = thpl2016$TotalHt, isPlantation = thpl2016$isPlantation, residual = abs(residuals(thplDiameterFromHeightRuark))), start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p, b1p not mutually significant
otherDiameterRuarkResidualPower = nlrob(residual ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = other2016$TotalHt, isPlantation = other2016$isPlantation, residual = abs(residuals(otherDiameterFromHeightRuark))), maxit = 100, start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p not significant

psmeDiameterSibbesenFormResidualPower = nlrob(residual ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = psme2016$TotalHt, isPlantation = psme2016$isPlantation, residual = abs(residuals(psmeDiameterFromHeightSibbesenForm))), start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p not significant
alruDiameterSibbesenFormResidualPower = nlrob(residual ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = alru2016$TotalHt, isPlantation = alru2016$isPlantation, residual = abs(residuals(alruDiameterFromHeightSibbesenForm))), start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p not significant
tsheDiameterSibbesenFormResidualPower = nlrob(residual ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = tshe2016$TotalHt, isPlantation = tshe2016$isPlantation, residual = abs(residuals(tsheDiameterFromHeightSibbesenForm))), start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p not significant
acmaDiameterSibbesenFormResidualPower = nlrob(residual ~ (a1 + a1p * isPlantation) * (TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = acma2016$TotalHt, isPlantation = acma2016$isPlantation, residual = abs(residuals(acmaDiameterFromHeightSibbesenForm))), start = list(a1 = 1, a1p = 0, b1 = 1, b1p = 0))
umcaDiameterSibbesenFormResidualPower = nlrob(residual ~ (a1 + a1p * isPlantation) * (TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = umca2016$TotalHt, isPlantation = umca2016$isPlantation, residual = abs(residuals(umcaDiameterFromHeightSibbesenForm))), start = list(a1 = 1, a1p = 0, b1 = 1, b1p = 0))
thplDiameterSibbesenFormResidualPower = nlrob(residual ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = thpl2016$TotalHt, isPlantation = thpl2016$isPlantation, residual = abs(residuals(thplDiameterFromHeightSibbesenForm))), start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p, b1p not mutually significant
otherDiameterSibbesenFormResidualPower = nlrob(residual ~ a1*(TotalHt - 1.37)^(b1 + b1p * isPlantation), tibble(TotalHt = other2016$TotalHt, isPlantation = other2016$isPlantation, residual = abs(residuals(otherDiameterFromHeightSibbesenForm))), maxit = 100, start = list(a1 = 1, b1 = 1, b1p = 0)) # a1p not significant

psmeDiameterChapmanFormResidualPower$confint = confint_nlrob(psmeDiameterChapmanFormResidualPower, level = 0.99, weights = rep(1, psmeDiameterChapmanFormResidualPower$nobs))
alruDiameterChapmanFormResidualPower$confint = confint_nlrob(alruDiameterChapmanFormResidualPower, level = 0.99, weights = rep(1, alruDiameterChapmanFormResidualPower$nobs))
tsheDiameterChapmanFormResidualPower$confint = confint_nlrob(tsheDiameterChapmanFormResidualPower, level = 0.99, weights = rep(1, tsheDiameterChapmanFormResidualPower$nobs))
acmaDiameterChapmanFormResidualPower$confint = confint_nlrob(acmaDiameterChapmanFormResidualPower, level = 0.99, weights = rep(1, acmaDiameterChapmanFormResidualPower$nobs))
umcaDiameterChapmanFormResidualPower$confint = confint_nlrob(umcaDiameterChapmanFormResidualPower, level = 0.99, weights = rep(1, umcaDiameterChapmanFormResidualPower$nobs))
thplDiameterChapmanFormResidualPower$confint = confint_nlrob(thplDiameterChapmanFormResidualPower, level = 0.99, weights = rep(1, thplDiameterChapmanFormResidualPower$nobs))
otherDiameterChapmanFormResidualPower$confint = confint_nlrob(otherDiameterChapmanFormResidualPower, level = 0.99, weights = rep(1, otherDiameterChapmanFormResidualPower$nobs))

psmeDiameterChapmanRichardsResidualPower$confint = confint_nlrob(psmeDiameterChapmanRichardsResidualPower, level = 0.99, weights = rep(1, psmeDiameterChapmanRichardsResidualPower$nobs))
alruDiameterChapmanRichardsResidualPower$confint = confint_nlrob(alruDiameterChapmanRichardsResidualPower, level = 0.99, weights = rep(1, alruDiameterChapmanRichardsResidualPower$nobs))
tsheDiameterChapmanRichardsResidualPower$confint = confint_nlrob(tsheDiameterChapmanRichardsResidualPower, level = 0.99, weights = rep(1, tsheDiameterChapmanRichardsResidualPower$nobs))
acmaDiameterChapmanRichardsResidualPower$confint = confint_nlrob(acmaDiameterChapmanRichardsResidualPower, level = 0.99, weights = rep(1, acmaDiameterChapmanRichardsResidualPower$nobs))
umcaDiameterChapmanRichardsResidualPower$confint = confint_nlrob(umcaDiameterChapmanRichardsResidualPower, level = 0.99, weights = rep(1, umcaDiameterChapmanRichardsResidualPower$nobs))
thplDiameterChapmanRichardsResidualPower$confint = confint_nlrob(thplDiameterChapmanRichardsResidualPower, level = 0.99, weights = rep(1, thplDiameterChapmanRichardsResidualPower$nobs))
otherDiameterChapmanRichardsResidualPower$confint = confint_nlrob(otherDiameterChapmanRichardsResidualPower, level = 0.99, weights = rep(1, otherDiameterChapmanRichardsResidualPower$nobs))

tsheDiameterRuarkResidualPower$confint = confint_nlrob(tsheDiameterRuarkResidualPower, level = 0.99, weights = rep(1, tsheDiameterRuarkResidualPower$nobs))
acmaDiameterRuarkResidualPower$confint = confint_nlrob(acmaDiameterRuarkResidualPower, level = 0.99, weights = rep(1, acmaDiameterRuarkResidualPower$nobs))
umcaDiameterRuarkResidualPower$confint = confint_nlrob(umcaDiameterRuarkResidualPower, level = 0.99, weights = rep(1, umcaDiameterRuarkResidualPower$nobs))
thplDiameterRuarkResidualPower$confint = confint_nlrob(thplDiameterRuarkResidualPower, level = 0.99, weights = rep(1, thplDiameterRuarkResidualPower$nobs))
otherDiameterRuarkResidualPower$confint = confint_nlrob(otherDiameterRuarkResidualPower, level = 0.99, weights = rep(1, otherDiameterRuarkResidualPower$nobs))

psmeDiameterSibbesenFormResidualPower$confint = confint_nlrob(psmeDiameterSibbesenFormResidualPower, level = 0.99, weights = rep(1, psmeDiameterSibbesenFormResidualPower$nobs))
alruDiameterSibbesenFormResidualPower$confint = confint_nlrob(alruDiameterSibbesenFormResidualPower, level = 0.99, weights = rep(1, alruDiameterSibbesenFormResidualPower$nobs))
tsheDiameterSibbesenFormResidualPower$confint = confint_nlrob(tsheDiameterSibbesenFormResidualPower, level = 0.99, weights = rep(1, tsheDiameterSibbesenFormResidualPower$nobs))
acmaDiameterSibbesenFormResidualPower$confint = confint_nlrob(acmaDiameterSibbesenFormResidualPower, level = 0.99, weights = rep(1, acmaDiameterSibbesenFormResidualPower$nobs))
umcaDiameterSibbesenFormResidualPower$confint = confint_nlrob(umcaDiameterSibbesenFormResidualPower, level = 0.99, weights = rep(1, umcaDiameterSibbesenFormResidualPower$nobs))
thplDiameterSibbesenFormResidualPower$confint = confint_nlrob(thplDiameterSibbesenFormResidualPower, level = 0.99, weights = rep(1, thplDiameterSibbesenFormResidualPower$nobs))
otherDiameterSibbesenFormResidualPower$confint = confint_nlrob(otherDiameterSibbesenFormResidualPower, level = 0.99, weights = rep(1, otherDiameterSibbesenFormResidualPower$nobs))

residualPower = tribble(~species, ~htName, ~ht_b1, ~ht_b1p, ~diaName, ~dia_b1, ~dia_b1p, ~ht_b1_min, ~ht_b1_max, ~ht_b1p_min, ~ht_b1p_max, ~dia_b1_min, ~dia_b1_max, ~dia_b1p_min, ~dia_b1p_max,
                        "PSME", "Chapman-Richards", psmeHeightChapmanRichardsResidualPower$m$getPars()["b1"], psmeHeightChapmanRichardsResidualPower$m$getPars()["b1p"], "Chapman-Richards form", psmeDiameterChapmanFormResidualPower$m$getPars()["b1"], psmeDiameterChapmanFormResidualPower$m$getPars()["b1p"], psmeHeightChapmanRichardsResidualPower$confint["b1", "0.5%"], psmeHeightChapmanRichardsResidualPower$confint["b1", "99.5%"], psmeHeightChapmanRichardsResidualPower$confint["b1p", "0.5%"], psmeHeightChapmanRichardsResidualPower$confint["b1p", "99.5%"], psmeDiameterChapmanFormResidualPower$confint["b1", "0.5%"], psmeDiameterChapmanFormResidualPower$confint["b1", "99.5%"], psmeDiameterChapmanFormResidualPower$confint["b1p", "0.5%"], psmeDiameterChapmanFormResidualPower$confint["b1p", "99.5%"],
                        "PSME", "Michaelis-Menten", psmeHeightMichaelisMentenResidualPower$m$getPars()["b1"], psmeHeightMichaelisMentenResidualPower$m$getPars()["b1p"], "Chapman-Richards", psmeDiameterChapmanRichardsResidualPower$m$getPars()["b1"], psmeDiameterChapmanRichardsResidualPower$m$getPars()["b1p"], psmeHeightMichaelisMentenResidualPower$confint["b1", "0.5%"], psmeHeightMichaelisMentenResidualPower$confint["b1", "99.5%"], psmeHeightMichaelisMentenResidualPower$confint["b1p", "0.5%"], psmeHeightMichaelisMentenResidualPower$confint["b1p", "99.5%"], psmeDiameterChapmanRichardsResidualPower$confint["b1", "0.5%"], psmeDiameterChapmanRichardsResidualPower$confint["b1", "99.5%"], psmeDiameterChapmanRichardsResidualPower$confint["b1p", "0.5%"], psmeDiameterChapmanRichardsResidualPower$confint["b1p", "99.5%"],
                        "PSME", "Sharma-Parton", psmeHeightSharmaPartonResidualPower$m$getPars()["b1"], psmeHeightSharmaPartonResidualPower$m$getPars()["b1p"], "Ruark", psmeDiameterRuarkResidualPower$m$getPars()["b1"], psmeDiameterRuarkResidualPower$m$getPars()["b1p"], psmeHeightSharmaPartonResidualPower$confint["b1", "0.5%"], psmeHeightSharmaPartonResidualPower$confint["b1", "99.5%"], psmeHeightSharmaPartonResidualPower$confint["b1p", "0.5%"], psmeHeightSharmaPartonResidualPower$confint["b1p", "99.5%"], psmeDiameterRuarkResidualPower$confint["b1", "0.5%"], psmeDiameterRuarkResidualPower$confint["b1", "99.5%"], psmeDiameterRuarkResidualPower$confint["b1p", "0.5%"], psmeDiameterRuarkResidualPower$confint["b1p", "99.5%"],
                        "PSME", "Sharma-Zhang", psmeHeightSharmaZhangResidualPower$m$getPars()["b1"], psmeHeightSharmaZhangResidualPower$m$getPars()["b1p"], "Sibbesen form", psmeDiameterSibbesenFormResidualPower$m$getPars()["b1"], psmeDiameterSibbesenFormResidualPower$m$getPars()["b1p"], psmeHeightSharmaZhangResidualPower$confint["b1", "0.5%"], psmeHeightSharmaZhangResidualPower$confint["b1", "99.5%"], psmeHeightSharmaZhangResidualPower$confint["b1p", "0.5%"], psmeHeightSharmaZhangResidualPower$confint["b1p", "99.5%"], psmeDiameterSibbesenFormResidualPower$confint["b1", "0.5%"], psmeDiameterSibbesenFormResidualPower$confint["b1", "99.5%"], psmeDiameterSibbesenFormResidualPower$confint["b1p", "0.5%"], psmeDiameterSibbesenFormResidualPower$confint["b1p", "99.5%"],
                        "ALRU2", "Chapman-Richards", alruHeightChapmanRichardsResidualPower$m$getPars()["b1"], alruHeightChapmanRichardsResidualPower$m$getPars()["b1p"], "Chapman-Richards form", alruDiameterChapmanFormResidualPower$m$getPars()["b1"], alruDiameterChapmanFormResidualPower$m$getPars()["b1p"], alruHeightChapmanRichardsResidualPower$confint["b1", "0.5%"], alruHeightChapmanRichardsResidualPower$confint["b1", "99.5%"], alruHeightChapmanRichardsResidualPower$confint["b1p", "0.5%"], alruHeightChapmanRichardsResidualPower$confint["b1p", "99.5%"], alruDiameterChapmanFormResidualPower$confint["b1", "0.5%"], alruDiameterChapmanFormResidualPower$confint["b1", "99.5%"], alruDiameterChapmanFormResidualPower$confint["b1p", "0.5%"], alruDiameterChapmanFormResidualPower$confint["b1p", "99.5%"],
                        "ALRU2", "Michaelis-Menten", alruHeightMichaelisMentenResidualPower$m$getPars()["b1"], alruHeightMichaelisMentenResidualPower$m$getPars()["b1p"], "Chapman-Richards", alruDiameterChapmanRichardsResidualPower$m$getPars()["b1"], alruDiameterChapmanRichardsResidualPower$m$getPars()["b1p"], alruHeightMichaelisMentenResidualPower$confint["b1", "0.5%"], alruHeightMichaelisMentenResidualPower$confint["b1", "99.5%"], alruHeightMichaelisMentenResidualPower$confint["b1p", "0.5%"], alruHeightMichaelisMentenResidualPower$confint["b1p", "99.5%"], alruDiameterChapmanRichardsResidualPower$confint["b1", "0.5%"], alruDiameterChapmanRichardsResidualPower$confint["b1", "99.5%"], alruDiameterChapmanRichardsResidualPower$confint["b1p", "0.5%"], alruDiameterChapmanRichardsResidualPower$confint["b1p", "99.5%"],
                        "ALRU2", "Sharma-Parton", alruHeightSharmaPartonResidualPower$m$getPars()["b1"], alruHeightSharmaPartonResidualPower$m$getPars()["b1p"], "Ruark", alruDiameterRuarkResidualPower$m$getPars()["b1"], alruDiameterRuarkResidualPower$m$getPars()["b1p"], alruHeightSharmaPartonResidualPower$confint["b1", "0.5%"], alruHeightSharmaPartonResidualPower$confint["b1", "99.5%"], alruHeightSharmaPartonResidualPower$confint["b1p", "0.5%"], alruHeightSharmaPartonResidualPower$confint["b1p", "99.5%"], alruDiameterRuarkResidualPower$confint["b1", "0.5%"], alruDiameterRuarkResidualPower$confint["b1", "99.5%"], alruDiameterRuarkResidualPower$confint["b1p", "0.5%"], alruDiameterRuarkResidualPower$confint["b1p", "99.5%"],
                        "ALRU2", "Sharma-Zhang", alruHeightSharmaZhangResidualPower$m$getPars()["b1"], alruHeightSharmaZhangResidualPower$m$getPars()["b1p"], "Sibbesen form", alruDiameterSibbesenFormResidualPower$m$getPars()["b1"], alruDiameterSibbesenFormResidualPower$m$getPars()["b1p"], alruHeightSharmaZhangResidualPower$confint["b1", "0.5%"], alruHeightSharmaZhangResidualPower$confint["b1", "99.5%"], alruHeightSharmaZhangResidualPower$confint["b1p", "0.5%"], alruHeightSharmaZhangResidualPower$confint["b1p", "99.5%"], alruDiameterSibbesenFormResidualPower$confint["b1", "0.5%"], alruDiameterSibbesenFormResidualPower$confint["b1", "99.5%"], alruDiameterSibbesenFormResidualPower$confint["b1p", "0.5%"], alruDiameterSibbesenFormResidualPower$confint["b1p", "99.5%"],
                        "TSHE", "Chapman-Richards", tsheHeightChapmanRichardsResidualPower$m$getPars()["b1"], tsheHeightChapmanRichardsResidualPower$m$getPars()["b1p"], "Chapman-Richards form", tsheDiameterChapmanFormResidualPower$m$getPars()["b1"], tsheDiameterChapmanFormResidualPower$m$getPars()["b1p"], tsheHeightChapmanRichardsResidualPower$confint["b1", "0.5%"], tsheHeightChapmanRichardsResidualPower$confint["b1", "99.5%"], NA_real_, NA_real_, tsheDiameterChapmanFormResidualPower$confint["b1", "0.5%"], tsheDiameterChapmanFormResidualPower$confint["b1", "99.5%"], tsheDiameterChapmanFormResidualPower$confint["b1p", "0.5%"], tsheDiameterChapmanFormResidualPower$confint["b1p", "99.5%"],
                        "TSHE", "Michaelis-Menten", tsheHeightMichaelisMentenResidualPower$m$getPars()["b1"], tsheHeightMichaelisMentenResidualPower$m$getPars()["b1p"], "Chapman-Richards", tsheDiameterChapmanRichardsResidualPower$m$getPars()["b1"], tsheDiameterChapmanRichardsResidualPower$m$getPars()["b1p"], tsheHeightMichaelisMentenResidualPower$confint["b1", "0.5%"], tsheHeightMichaelisMentenResidualPower$confint["b1", "99.5%"], NA_real_, NA_real_, tsheDiameterChapmanRichardsResidualPower$confint["b1", "0.5%"], tsheDiameterChapmanRichardsResidualPower$confint["b1", "99.5%"], tsheDiameterChapmanRichardsResidualPower$confint["b1p", "0.5%"], tsheDiameterChapmanRichardsResidualPower$confint["b1p", "99.5%"],
                        "TSHE", "Sharma-Parton", tsheHeightSharmaPartonResidualPower$m$getPars()["b1"], tsheHeightSharmaPartonResidualPower$m$getPars()["b1p"], "Ruark", tsheDiameterRuarkResidualPower$m$getPars()["b1"], tsheDiameterRuarkResidualPower$m$getPars()["b1p"], tsheHeightSharmaPartonResidualPower$confint["b1", "0.5%"], tsheHeightSharmaPartonResidualPower$confint["b1", "99.5%"], NA_real_, NA_real_, tsheDiameterRuarkResidualPower$confint["b1", "0.5%"], tsheDiameterRuarkResidualPower$confint["b1", "99.5%"], tsheDiameterRuarkResidualPower$confint["b1p", "0.5%"], tsheDiameterRuarkResidualPower$confint["b1p", "99.5%"],
                        "TSHE", "Sharma-Zhang", tsheHeightSharmaZhangResidualPower$m$getPars()["b1"], tsheHeightSharmaZhangResidualPower$m$getPars()["b1p"], "Sibbesen form", tsheDiameterSibbesenFormResidualPower$m$getPars()["b1"], tsheDiameterSibbesenFormResidualPower$m$getPars()["b1p"], tsheHeightSharmaZhangResidualPower$confint["b1", "0.5%"], tsheHeightSharmaZhangResidualPower$confint["b1", "99.5%"], NA_real_, NA_real_, tsheDiameterSibbesenFormResidualPower$confint["b1", "0.5%"], tsheDiameterSibbesenFormResidualPower$confint["b1", "99.5%"], tsheDiameterSibbesenFormResidualPower$confint["b1p", "0.5%"], tsheDiameterSibbesenFormResidualPower$confint["b1p", "99.5%"],
                        "ACMA3", "Chapman-Richards", acmaHeightChapmanRichardsResidualPower$m$getPars()["b1"], acmaHeightChapmanRichardsResidualPower$m$getPars()["b1p"], "Chapman-Richards form", acmaDiameterChapmanFormResidualPower$m$getPars()["b1"], acmaDiameterChapmanFormResidualPower$m$getPars()["b1p"], acmaHeightChapmanRichardsResidualPower$confint["b1", "0.5%"], acmaHeightChapmanRichardsResidualPower$confint["b1", "99.5%"], NA_real_, NA_real_, acmaDiameterChapmanFormResidualPower$confint["b1", "0.5%"], acmaDiameterChapmanFormResidualPower$confint["b1", "99.5%"], acmaDiameterChapmanFormResidualPower$confint["b1p", "0.5%"], acmaDiameterChapmanFormResidualPower$confint["b1p", "99.5%"],
                        "ACMA3", "Michaelis-Menten", acmaHeightMichaelisMentenResidualPower$m$getPars()["b1"], acmaHeightMichaelisMentenResidualPower$m$getPars()["b1p"], "Chapman-Richards", acmaDiameterChapmanRichardsResidualPower$m$getPars()["b1"], acmaDiameterChapmanRichardsResidualPower$m$getPars()["b1p"], acmaHeightMichaelisMentenResidualPower$confint["b1", "0.5%"], acmaHeightMichaelisMentenResidualPower$confint["b1", "99.5%"], NA_real_, NA_real_, acmaDiameterChapmanRichardsResidualPower$confint["b1", "0.5%"], acmaDiameterChapmanRichardsResidualPower$confint["b1", "99.5%"], acmaDiameterChapmanRichardsResidualPower$confint["b1p", "0.5%"], acmaDiameterChapmanRichardsResidualPower$confint["b1p", "99.5%"],
                        "ACMA3", "Sharma-Parton", acmaHeightSharmaPartonResidualPower$m$getPars()["b1"], acmaHeightSharmaPartonResidualPower$m$getPars()["b1p"], "Ruark", acmaDiameterRuarkResidualPower$m$getPars()["b1"], acmaDiameterRuarkResidualPower$m$getPars()["b1p"], acmaHeightSharmaPartonResidualPower$confint["b1", "0.5%"], acmaHeightSharmaPartonResidualPower$confint["b1", "99.5%"], NA_real_, NA_real_, acmaDiameterRuarkResidualPower$confint["b1", "0.5%"], acmaDiameterRuarkResidualPower$confint["b1", "99.5%"], acmaDiameterRuarkResidualPower$confint["b1p", "0.5%"], acmaDiameterRuarkResidualPower$confint["b1p", "99.5%"],
                        "ACMA3", "Sharma-Zhang", acmaHeightSharmaZhangResidualPower$m$getPars()["b1"], acmaHeightSharmaZhangResidualPower$m$getPars()["b1p"], "Sibbesen form", acmaDiameterSibbesenFormResidualPower$m$getPars()["b1"], acmaDiameterSibbesenFormResidualPower$m$getPars()["b1p"], acmaHeightSharmaZhangResidualPower$confint["b1", "0.5%"], acmaHeightSharmaZhangResidualPower$confint["b1", "99.5%"], NA_real_, NA_real_, acmaDiameterSibbesenFormResidualPower$confint["b1", "0.5%"], acmaDiameterSibbesenFormResidualPower$confint["b1", "99.5%"], acmaDiameterSibbesenFormResidualPower$confint["b1p", "0.5%"], acmaDiameterSibbesenFormResidualPower$confint["b1p", "99.5%"],
                        "UMCA", "Chapman-Richards", umcaHeightChapmanRichardsResidualPower$m$getPars()["b1"], umcaHeightChapmanRichardsResidualPower$m$getPars()["b1p"], "Chapman-Richards form", umcaDiameterChapmanFormResidualPower$m$getPars()["b1"], umcaDiameterChapmanFormResidualPower$m$getPars()["b1p"], umcaHeightChapmanRichardsResidualPower$confint["b1", "0.5%"], umcaHeightChapmanRichardsResidualPower$confint["b1", "99.5%"], NA_real_, NA_real_, umcaDiameterChapmanFormResidualPower$confint["b1", "0.5%"], umcaDiameterChapmanFormResidualPower$confint["b1", "99.5%"], umcaDiameterChapmanFormResidualPower$confint["b1p", "0.5%"], umcaDiameterChapmanFormResidualPower$confint["b1p", "99.5%"],
                        "UMCA", "Michaelis-Menten", umcaHeightMichaelisMentenResidualPower$m$getPars()["b1"], umcaHeightMichaelisMentenResidualPower$m$getPars()["b1p"], "Chapman-Richards", umcaDiameterChapmanRichardsResidualPower$m$getPars()["b1"], umcaDiameterChapmanRichardsResidualPower$m$getPars()["b1p"], umcaHeightMichaelisMentenResidualPower$confint["b1", "0.5%"], umcaHeightMichaelisMentenResidualPower$confint["b1", "99.5%"], NA_real_, NA_real_, umcaDiameterChapmanRichardsResidualPower$confint["b1", "0.5%"], umcaDiameterChapmanRichardsResidualPower$confint["b1", "99.5%"], umcaDiameterChapmanRichardsResidualPower$confint["b1p", "0.5%"], umcaDiameterChapmanRichardsResidualPower$confint["b1p", "99.5%"],
                        "UMCA", "Sharma-Parton", umcaHeightSharmaPartonResidualPower$m$getPars()["b1"], umcaHeightSharmaPartonResidualPower$m$getPars()["b1p"], "Ruark", umcaDiameterRuarkResidualPower$m$getPars()["b1"], umcaDiameterRuarkResidualPower$m$getPars()["b1p"], umcaHeightSharmaPartonResidualPower$confint["b1", "0.5%"], umcaHeightSharmaPartonResidualPower$confint["b1", "99.5%"], NA_real_, NA_real_, umcaDiameterRuarkResidualPower$confint["b1", "0.5%"], umcaDiameterRuarkResidualPower$confint["b1", "99.5%"], umcaDiameterRuarkResidualPower$confint["b1p", "0.5%"], umcaDiameterRuarkResidualPower$confint["b1p", "99.5%"],
                        "UMCA", "Sharma-Zhang", umcaHeightSharmaZhangResidualPower$m$getPars()["b1"], umcaHeightSharmaZhangResidualPower$m$getPars()["b1p"], "Sibbesen form", umcaDiameterSibbesenFormResidualPower$m$getPars()["b1"], umcaDiameterSibbesenFormResidualPower$m$getPars()["b1p"], umcaHeightSharmaZhangResidualPower$confint["b1", "0.5%"], umcaHeightSharmaZhangResidualPower$confint["b1", "99.5%"], NA_real_, NA_real_, umcaDiameterSibbesenFormResidualPower$confint["b1", "0.5%"], umcaDiameterSibbesenFormResidualPower$confint["b1", "99.5%"], umcaDiameterSibbesenFormResidualPower$confint["b1p", "0.5%"], umcaDiameterSibbesenFormResidualPower$confint["b1p", "99.5%"],
                        "THPL", "Chapman-Richards", thplHeightChapmanRichardsResidualPower$m$getPars()["b1"], thplHeightChapmanRichardsResidualPower$m$getPars()["b1p"], "Chapman-Richards form", thplDiameterChapmanFormResidualPower$m$getPars()["b1"], thplDiameterChapmanFormResidualPower$m$getPars()["b1p"], thplHeightChapmanRichardsResidualPower$confint["b1", "0.5%"], thplHeightChapmanRichardsResidualPower$confint["b1", "99.5%"], NA_real_, NA_real_, thplDiameterChapmanFormResidualPower$confint["b1", "0.5%"], thplDiameterChapmanFormResidualPower$confint["b1", "99.5%"], thplDiameterChapmanFormResidualPower$confint["b1p", "0.5%"], thplDiameterChapmanFormResidualPower$confint["b1p", "99.5%"],
                        "THPL", "Michaelis-Menten", thplHeightMichaelisMentenResidualPower$m$getPars()["b1"], thplHeightMichaelisMentenResidualPower$m$getPars()["b1p"], "Chapman-Richards", thplDiameterChapmanRichardsResidualPower$m$getPars()["b1"], thplDiameterChapmanRichardsResidualPower$m$getPars()["b1p"], thplHeightMichaelisMentenResidualPower$confint["b1", "0.5%"], thplHeightMichaelisMentenResidualPower$confint["b1", "99.5%"], NA_real_, NA_real_, thplDiameterChapmanRichardsResidualPower$confint["b1", "0.5%"], thplDiameterChapmanRichardsResidualPower$confint["b1", "99.5%"], thplDiameterChapmanRichardsResidualPower$confint["b1p", "0.5%"], thplDiameterChapmanRichardsResidualPower$confint["b1p", "99.5%"],
                        "THPL", "Sharma-Parton", thplHeightSharmaPartonResidualPower$m$getPars()["b1"], thplHeightSharmaPartonResidualPower$m$getPars()["b1p"], "Ruark", thplDiameterRuarkResidualPower$m$getPars()["b1"], thplDiameterRuarkResidualPower$m$getPars()["b1p"], thplHeightSharmaPartonResidualPower$confint["b1", "0.5%"], thplHeightSharmaPartonResidualPower$confint["b1", "99.5%"], NA_real_, NA_real_, thplDiameterRuarkResidualPower$confint["b1", "0.5%"], thplDiameterRuarkResidualPower$confint["b1", "99.5%"], thplDiameterRuarkResidualPower$confint["b1p", "0.5%"], thplDiameterRuarkResidualPower$confint["b1p", "99.5%"],
                        "THPL", "Sharma-Zhang", thplHeightSharmaZhangResidualPower$m$getPars()["b1"], thplHeightSharmaZhangResidualPower$m$getPars()["b1p"], "Sibbesen form", thplDiameterSibbesenFormResidualPower$m$getPars()["b1"], thplDiameterSibbesenFormResidualPower$m$getPars()["b1p"], thplHeightSharmaZhangResidualPower$confint["b1", "0.5%"], thplHeightSharmaZhangResidualPower$confint["b1", "99.5%"], NA_real_, NA_real_, thplDiameterSibbesenFormResidualPower$confint["b1", "0.5%"], thplDiameterSibbesenFormResidualPower$confint["b1", "99.5%"], thplDiameterSibbesenFormResidualPower$confint["b1p", "0.5%"], thplDiameterSibbesenFormResidualPower$confint["b1p", "99.5%"],
                        "other", "Chapman-Richards", otherHeightChapmanRichardsResidualPower$m$getPars()["b1"], otherHeightChapmanRichardsResidualPower$m$getPars()["b1p"], "Chapman-Richards form", otherDiameterChapmanFormResidualPower$m$getPars()["b1"], otherDiameterChapmanFormResidualPower$m$getPars()["b1p"], otherHeightChapmanRichardsResidualPower$confint["b1", "0.5%"], otherHeightChapmanRichardsResidualPower$confint["b1", "99.5%"], otherHeightChapmanRichardsResidualPower$confint["b1p", "0.5%"], otherHeightChapmanRichardsResidualPower$confint["b1p", "99.5%"], otherDiameterChapmanFormResidualPower$confint["b1", "0.5%"], otherDiameterChapmanFormResidualPower$confint["b1", "99.5%"], otherDiameterChapmanFormResidualPower$confint["b1p", "0.5%"], otherDiameterChapmanFormResidualPower$confint["b1p", "99.5%"],
                        "other", "Michaelis-Menten", otherHeightMichaelisMentenResidualPower$m$getPars()["b1"], otherHeightMichaelisMentenResidualPower$m$getPars()["b1p"], "Chapman-Richards", otherDiameterChapmanRichardsResidualPower$m$getPars()["b1"], otherDiameterChapmanRichardsResidualPower$m$getPars()["b1p"], otherHeightMichaelisMentenResidualPower$confint["b1", "0.5%"], otherHeightMichaelisMentenResidualPower$confint["b1", "99.5%"], otherHeightMichaelisMentenResidualPower$confint["b1p", "0.5%"], otherHeightMichaelisMentenResidualPower$confint["b1p", "99.5%"], otherDiameterChapmanRichardsResidualPower$confint["b1", "0.5%"], otherDiameterChapmanRichardsResidualPower$confint["b1", "99.5%"], otherDiameterChapmanRichardsResidualPower$confint["b1p", "0.5%"], otherDiameterChapmanRichardsResidualPower$confint["b1p", "99.5%"],
                        "other", "Sharma-Parton", otherHeightSharmaPartonResidualPower$m$getPars()["b1"], otherHeightSharmaPartonResidualPower$m$getPars()["b1p"], "Ruark", otherDiameterRuarkResidualPower$m$getPars()["b1"], otherDiameterRuarkResidualPower$m$getPars()["b1p"], otherHeightSharmaPartonResidualPower$confint["b1", "0.5%"], otherHeightSharmaPartonResidualPower$confint["b1", "99.5%"], otherHeightSharmaPartonResidualPower$confint["b1p", "0.5%"], otherHeightSharmaPartonResidualPower$confint["b1p", "99.5%"], otherDiameterRuarkResidualPower$confint["b1", "0.5%"], otherDiameterRuarkResidualPower$confint["b1", "99.5%"], otherDiameterRuarkResidualPower$confint["b1p", "0.5%"], otherDiameterRuarkResidualPower$confint["b1p", "99.5%"],
                        "other", "Sharma-Zhang", otherHeightSharmaZhangResidualPower$m$getPars()["b1"], otherHeightSharmaZhangResidualPower$m$getPars()["b1p"], "Sibbesen form", otherDiameterSibbesenFormResidualPower$m$getPars()["b1"], otherDiameterSibbesenFormResidualPower$m$getPars()["b1p"], otherHeightSharmaZhangResidualPower$confint["b1", "0.5%"], otherHeightSharmaZhangResidualPower$confint["b1", "99.5%"], otherHeightSharmaZhangResidualPower$confint["b1p", "0.5%"], otherHeightSharmaZhangResidualPower$confint["b1p", "99.5%"], otherDiameterSibbesenFormResidualPower$confint["b1", "0.5%"], otherDiameterSibbesenFormResidualPower$confint["b1", "99.5%"], otherDiameterSibbesenFormResidualPower$confint["b1p", "0.5%"], otherDiameterSibbesenFormResidualPower$confint["b1p", "99.5%"]) %>%
  mutate(species = factor(species, labels = c("Douglas-fir", "western redcedar", "western hemlock", "red alder", "bigleaf maple", "Oregon myrtle", "other species"),  levels = c("PSME", "THPL", "TSHE", "ALRU2", "ACMA3", "UMCA", "other")),
         ht_b1p_min = ht_b1_min + ht_b1p_min + sqrt(2 * (ht_b1 - ht_b1_min) * (ht_b1p - ht_b1p_min)), # shift confidence intervals from plantation effects to combined effects: the covariance is equal and opposite the main effect variance
         ht_b1p_max = ht_b1_max + ht_b1p_max - sqrt(2 * (ht_b1 - ht_b1_max) * (ht_b1p - ht_b1p_max)),
         dia_b1p_min = dia_b1_min + dia_b1p_min + sqrt(2 * (dia_b1 - dia_b1_min) * (dia_b1p - dia_b1p_min)), 
         dia_b1p_max = dia_b1_max + dia_b1p_max - sqrt(2 * (dia_b1 - dia_b1_max) * (dia_b1p - dia_b1p_max)))
#residualPower %>% mutate(sum_center = ht_b1 + ht_b1p, sum_min = ht_b1_min + ht_b1p_min, ht_b1p_min2 = ht_b1_min + ht_b1p_min + sqrt(2*(ht_b1 - ht_b1_min) * (ht_b1p - ht_b1p_min))) %>% select(species, ht_b1_min, ht_b1, ht_b1p_min, ht_b1p, sum_min, ht_b1p_min2, sum_center)
residualPower %>% select(species, ht_b1, ht_b1p, dia_b1, dia_b1p) %>%
  mutate(ht_b1p = ht_b1 + ht_b1p, dia_b1p = dia_b1 + dia_b1p, ht_b1 = ht_b1, dia_b1 = dia_b1) %>% 
  group_by(species) %>% 
  summarize(ht_b1 = round(2 * mean(ht_b1), 1), ht_b1p = round(2 * mean(ht_b1p), 1), # Table S3
            dia_b1 = round(2 * mean(dia_b1), 1), dia_b1p = round(2 * mean(dia_b1p), 1))
residualPower %>% summarize(ht_b1 = mean(ht_b1), ht_b1p = mean(ht_b1 + if_else(is.na(ht_b1p), 0, ht_b1p)), dia_b1 = mean(dia_b1), dia_b1p = mean(dia_b1 + dia_b1p))

# Figure S6 in HtDia figures.R